export const KEYWORDSUPLOAD_INIT = 'KEYWORDSUPLOAD_INIT'
export const KEYWORDSUPLOAD_CHANGE_ROWS = 'KEYWORDSUPLOAD_CHANGE_ROWS'
export const KEYWORDSUPLOAD_CHANGE_INITED = 'KEYWORDSUPLOAD_CHANGE_INITED'