
<link rel = "stylesheet" href = "/css/bootstrap-table.css?v=20170719">
<link rel = "stylesheet" href = "/css/bootstrap-editable.css">
<link rel = "stylesheet" href = "/css/bootstrap-switch.min.css"/>

<link rel = "stylesheet" href = "/css/datepicker.css"/>

<script type="text/javascript" src="/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="/js/echarts.js"></script>
<script type="text/javascript" src="/js/china.js"></script>
<script type="text/javascript" src="/js/bootstrap-tableFilter-deepleaper.js?v=20170502"></script>
