<form id="add" method="post" action="/media/categorysave" class="form-horizontal list-form" novalidate="novalidate">

    <div class="form-group ">

        <label class="col-sm-3 control-label">分类名称</label>
        <div class="col-sm-6 ">
            <input id="name" type="text" name="name" class="form-control" check-type="required" required-message="不能为空。">
        </div>
    </div>

   

    <div class="form-group ">
        <label class="col-sm-3 control-label">备注</label>
        <div class="col-sm-6 ">
            <input type="text" class="form-control" name="info" id="info" value="" >
        </div>
    </div>

   
    
</form>