<?php 
    $name   = $this->item['name'];
    $uid    = $this->item['uid'];
    $info    = $this->item['info'];

?>

<form id="edit" method="post" action="/order/ordersave" class="form-horizontal list-form" novalidate="novalidate">

    <div class="form-group ">
        <label class="col-sm-3 control-label">订单名称</label>
        <div class="col-sm-6 ">
           
            <div><?php echo $name;?></div>
        </div>
    </div>
     
    <div class="form-group ">
        <label class="col-sm-3 control-label">订单号</label>
        <div class="col-sm-6 ">
           
           <div><?php echo $this->item['order_id'];?></div>
        </div>
    </div>
    
     <div class="form-group " style="display: none">
        <label class="col-sm-3 control-label">投放量</label>
        <div class="col-sm-6 ">
            
            <div><?php echo $this->item['cpm'];?></div>
        </div>
    </div>
    
   
    <div class="form-group ">
        <label class="col-sm-3 control-label">订单周期</label>
        <div class="col-sm-6 ">
            <?php echo $this->item['s'];?> 至 <?php echo $this->item['e'];?>
        </div>
    </div>
    
    <div class="form-group ">
        <label class="col-sm-3 control-label">客户</label>
        <div class="col-sm-6 ">
            
				<?php foreach($this->client_menu as $key => $val):?>
				 <?php if($this->item['client'] ==$key) echo $val;?>
				<?php endforeach;?>
           
        </div>
    </div>
    
   
    <div class="form-group " style="display: none">
        <label class="col-sm-3 control-label">负责人</label>
        <div class="col-sm-6 ">
            
        	
				<?php foreach($this->user_menu as $key => $val):?>
				<?php if($this->item['duty_user'] ==$key) echo $val;?>
				<?php endforeach;?>
            </select>
        </div>
    </div>
    
    <div class="form-group ">
        <label class="col-sm-3 control-label">订单说明</label>
        <div class="col-sm-6 ">
            
             <div><?php echo $this->item['info'];?></div>
        </div>
    </div>
    
    <div class="form-group ">
        <label class="col-sm-3 control-label">创建</label>
        <div class="col-sm-6 ">
            <div><?php foreach($this->user_menu as $key => $val):?>
				<?php if($this->item['create_user'] ==$key) echo $val;?>
				<?php endforeach;?> 创建于 <?php echo date("Y-m-h H:i:s",$this->item['create_time']);?> </div>
        </div>
    </div>
    
    <div class="form-group ">
        <label class="col-sm-3 control-label">修改</label>
        <div class="col-sm-6 ">
            <div><?php foreach($this->user_menu as $key => $val):?>
				<?php if($this->item['edit_user'] ==$key) echo $val;?>
				<?php endforeach;?> 修改于 <?php echo date("Y-m-h H:i:s",$this->item['edit_time']);?> </div>
        </div>
    </div>
    
</form>


<script type="text/javascript">

    checkActionAuth('/order/order', 1);
</script>
