<?php
echo $this->partial('layout/listPublicHeader2.phtml');
echo $this->partial('layout/tablePublic.phtml');
?>
<script>

    var ListPageConfig = {
        tableId: '#table',   // 表格id
        func: function (data) {
        },
        tableIndexCol: 'uid', //数据索引字段 一般为 uid 或者 id
        table: {           //表格配置
            url: '/order/targeting',
            queryParams: 'queryParams',
            toolbar: '#toolbar',
            showColumns: true,
            searchAlign: 'left',
            pagination: true,
            pageSize: 50,
            pageList: [30, 50, 100],
            showRefresh: true,
            sortOrder: 'desc',
            sortName: 'create_time',
            sidePagination: 'server',
            striped: true,
            cookie: true,
            cookieIdTable: 'replacebyListJS',
            cookiesEnabled: ['bs.table.pageNumber'],
            cookiePath: '/',

            columns: [{
                checkbox: true
            }, {
                field: 'name',
                title: '定向策略名称'
            }, {
                field: 'info',
                title: '说明'

            }, {
                field: 'create_time',
                title: '创建日期'

            }, {
                field: 'user_name',
                title: '创建/修改人'


            }, {
                field: 'do',
                title: '操作',
                align: 'center',
                formatter: 'List.operateFormatter',
                events: 'List.operateEvents',
                width: '100px'
            }]
        },
        url: {
            add: '/order/targetingadd',         //添加 数据 html 地址
            edit: '/order/targetingedit',         //编辑数据 html 地址
            del: '/order/targetingdel',         //删除数据地址
            detail: '/order/targetingdetail'                //详细内容地址,为空则取编辑的地址
        },
        title: {
            addTitle: '添加定向及播控策略',
            editTitle: '编辑定向及播控策略',
            detailTitle: '编辑定向及播控策略'
        },
        showDetail: false         //是否显示详细信息按钮
    };

    var auth = getAuthorityByUrl('/order/targeting');
    function checkAuthority() {
        if (auth == 0) {
            ListPageConfig.action = {
                detail: false,
                edit: false,
                del: false
            };
            toFirstLegalPage();
        } else if (auth == 1) {
            ListPageConfig.action = {
                detail: true,
                edit: false,
                del: false
            };
        } else if (auth == 2) {
            ListPageConfig.action = {
                detail: true,
                edit: true,
                del: false
            };
        }
    }
    checkAuthority();
</script>

<div id="toolbar">
    <div class="btn-group pull-left" id="for_change">
        <div class="btn deepleaper-btn-normal plus">
            <img src="/img/icon/icon_plussign.png" class="btn-icon">添加定向
        </div>
    </div>
    <div class="input-group pull-left deepleaper-search-control" style='width:250px;'>
        <input type="text" id="searchKeyword" class="form-control" placeholder="定向策略名称" value="" name="search">
        <span class="input-group-btn">
			<a id="ok" class="btn btn-default dropdown-toggle deepleaper-search-btn" type="button" data-toggle="dropdown">
                <span class="glyphicon glyphicon-search"></span>
            </a>
		</span>
    </div>
</div>

<table id="table" class="list-table"></table>
<?php
echo $this->partial('layout/listPublicFooter3.phtml');
?>
<script>
    hideChangeBtnIfNeed(auth);
</script>