<script type="text/javascript" src="/js/bootstrap-table-modify.js?v=20170721"></script>
<script type="text/javascript" src="/js/bootstrap-table-cookie.js"></script>
<script type="text/javascript" src="/js/bootstrap-editable.js"></script>
<script type="text/javascript" src="/js/bootstrap-table-editable.js"></script>
<!--<script type="text/javascript" src="/js/bootstrap-table-filter-control.js"></script>-->
<script type="text/javascript" src="/js/bootstrap-table-zh-CN.js"></script>
<!--<script type="text/javascript" src="/js/bootstrap-validation.js"></script>-->

<script type="text/javascript" src="/js/bootstrap-switch.js"></script>
<script type="text/javascript" src="/js/listAd.js?v=20170407"></script>
<script type="text/javascript" src="/js/layer/layer.js"></script>
<script type="text/javascript" src="/js/dl-custom-filter.js"></script>