<?php
$this->headTitle('无法找到访问的页面');
?>
<table width="950" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="150" height="150" align="center">
     <img src="/img/notfound.png" border="0">
    </td>
    
    <td width="220" align="left" class="main_alert">
    <DIV id="errorMessage">
    404错误
    </div>
    抱歉，无法找到您要访问的页面！
    <DIV id="errorHome">
	<A href="/">返回登录界面</A>
	</DIV>
    </td>
    <td width="30" valign="top" align="left">
    <img src="/img/loginsep.png" border="0">
    </td>
    <td>
	<img src="/img/deepleaper_logo.png" border="0">
    </td>
  </tr>
</table>




