<!--广告创意列表-->
<link rel="stylesheet" href="/css/bootstrap-table.css?v=20170719">
<link rel="stylesheet" href="/css/datepicker.css"/>
<style>
    details summary {
        cursor: pointer;
    }
    details summary:focus {
        outline: none;
    }
    details div {
        padding-left: 18px;
    }
    .bootstrap-table {
        height: calc(100% - 60px);
        overflow: hidden;
    }
    .bootstrap-table .fixed-table-container {
        height: calc(100% - 150px);
    }
    .bootstrap-table .fixed-table-body {
        overflow: auto;
        min-height: 230px;
    }
    .bootstrap-table .fixed-table-body .fixed-table-loading {
        top: 0 !important;
        height: 100%;
        padding-top: 80px;
        font-size: 14px;
        background-color: rgba(255,255,255,0.85);
    }
    .thead-position {
        position: absolute;
        z-index: 999;
        top: 0;
    }
    .tbody-block {
        display: block;
    }
    table td:not(:hover) .ad-table-edit-open {
        visibility: hidden !important;
    }
</style>
<?php
echo $this->renderFile('@app/views/layouts/formPublicHeader.phtml');
?>
<script type="text/javascript" src="/js/bootstrap-tableFilter-deepleaper.js"></script>
<?php
echo $this->renderFile('@app/views/layouts/tablePublic.phtml');
?>

<div class="user-message-list">
    <div class="user-message-list-name">
        <ol>
            <li>
                <span id="companyName" class="user-message-name linkable"></span>
                <img class="separator hidden" src="/img/arrow.png">
                <span id="adgroupName" class="user-message-name linkable hidden"></span>
                <img class="separator hidden" src="/img/arrow.png">
                <span id="adplanName" class="user-message-name hidden"></span>
            </li>
        </ol>
    </div>
</div>
<div class="Dl-fullscreen-line"></div>
<input type="hidden" name="plan_id" id="plan_id">
<div class="toolbar" id="toolbar">
    <div class="btn-group pull-left create" id="for_change">
        <div class="btn deepleaper-btn-normal ignore-plus" id="add-new-open">
            <img src="/img/icon/icon_plussign.png" class="btn-icon">新建广告创意
        </div>
    </div>

    <div class="input-group pull-left deepleaper-search-control" style='width:250px;margin-right: 14px;'>
        <input type="text" id="searchKeyword" class="form-control" placeholder="请输入广告创意名称" value=""
               name="search">
        <span class="input-group-btn">
            <a id="ok" class="btn btn-default dropdown-toggle deepleaper-search-btn" type="button"
               data-toggle="dropdown">
                <span class="glyphicon glyphicon-search"></span>
            </a>
        </span>
    </div>

    <div class="input-group pull-left date dl-date-range-wrapper" style="margin-left: 30px">
        <input type="text" class="form-control dl-date-range-input" id="searchDate">
        <span class="caret dl-date-range-input-icon"></span>
    </div>
    
    <!-- 批量操作开始 -->
    <br/>
    <div class="input-group pull-left" style="margin-top: 8px;" id="all-update">
        <a class="btn" data-status="active" style="color: #337ab7;" href="javascript:;">启用</a>
        <a class="btn" data-status="pause" style="color: #337ab7;" href="javascript:;">暂停</a>
        <a class="btn" data-status="delete" style="color: #337ab7;" href="javascript:;">删除</a>
    </div>
    <div class="input-group pull-left" style="margin-top: 8px;">
        <button style="margin-left: 6px;" type="button" class="btn deepleaper-btn-normal" data-toggle="dropdown" aria-expanded="true" id="dropdownMenu1">
            <div style="text-align: center;">
                <span>批量操作</span>
                <span class="caret"></span>
            </div>
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <li><a href="javascript:;" id="all-title-open">修改创意标题/描述</a></li>
            <li><a href="javascript:;" id="all-url-open">修改创意URL</a></li>
            <li><a href="javascript:;" id="all-copy-open">复制广告创意</a></li>
        </ul>
    </div>
    <!-- 批量操作结束 -->
</div>

<!-- 新建广告创意模态框 -->
<div class="modal fade" id="add-new-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="margin-top: 155px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">选择广告计划</h4>
            </div>
            <div class="modal-body">
                <div class="input-group data-search" style="width: 200px;padding: 6px;">
                    <input type="text" class="form-control" placeholder="搜索广告计划">
                    <div class="input-group-addon btn btn-primary">搜索</div>
                </div>
                <div style="max-height: 300px;overflow: auto;">
                    <div class="data-main" style="display: table;padding: 12px 6px;"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="add-new">提交</button>
            </div>
        </div>
    </div>
</div>

<!-- 修改创意标题模态框 -->
<div class="modal fade" id="all-title-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="margin-top: 155px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="col-md-2 col-md-offset-1 control-label" style="margin-top: 10px;">修改创意标题：</label>
                    <div class="col-md-7">
                        <textarea class="form-control dl-notNull creativeTitle" maxlength="50" placeholder="2-23个字"></textarea>
                    </div>
                    <span class="help-block col-md-7 col-md-offset-3"></span>
                </div>
                <div class="form-group">
                    <label class="col-md-2 col-md-offset-1 control-label" style="margin-top: 10px;">修改创意描述：</label>
                    <div class="col-md-7">
                        <textarea class="form-control dl-notNull creativeTitle" maxlength="50" placeholder="2-23个字"></textarea>
                    </div>
                    <span class="help-block col-md-7 col-md-offset-3"></span>
                </div>
                <div style="clear: both;height: 1px;"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="all-title">提交</button>
            </div>
        </div>
    </div>
</div>

<!-- 修改创意URL模态框 -->
<div class="modal fade" id="all-url-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="margin-top: 155px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div style="width: 100%;display: table;">
                    <div style="display: table-row;">
                        <div style="display: table-cell;text-align: right;">修改URL为：</div>
                        <input style="margin-top: 6px;width: 300px;display: table-cell;padding: 6px 12px;font-size: 12px;color: #555;border: 1px solid #ccc;border-radius: 6px;" placeholder="请填写以http(https)开头的有效着陆页"/>
                    </div>
                    <div style="display: table-row;">
                        <div style="display: table-cell;text-align: right;">修改第三方曝光监测链接为：</div>
                        <input style="margin-top: 6px;width: 300px;display: table-cell;padding: 6px 12px;font-size: 12px;color: #555;border: 1px solid #ccc;border-radius: 6px;" placeholder="请填写以http(https)开头的有效第三方曝光监测链接"/>
                    </div>
                    <div style="display: table-row;">
                        <div style="display: table-cell;text-align: right;">修改第三方点击监测链接为：</div>
                        <input style="margin-top: 6px;width: 300px;display: table-cell;padding: 6px 12px;font-size: 12px;color: #555;border: 1px solid #ccc;border-radius: 6px;" placeholder="请填写以http(https)开头的有效第三方点击监测链接"/>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="all-url">提交</button>
            </div>
        </div>
    </div>
</div>

<!-- 复制模态框 -->
<div class="modal fade" id="all-copy-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="margin-top: 155px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div class="input-group data-search" style="width: 200px;padding: 6px;">
                    <input type="text" class="form-control" placeholder="搜索广告计划">
                    <div class="input-group-addon btn btn-primary">搜索</div>
                </div>
                <div style="padding-left: 6px;">选择广告计划</div>
                <div style="max-height: 300px;overflow: auto;">
                    <div class="data-main" style="display: table;padding: 12px 6px;"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="all-copy">提交</button>
            </div>
        </div>
    </div>
</div>

<table id="table" class="list-table"></table>
<?php
echo $this->renderFile('@app/views/layouts/bootstrapDaterangerpickerPublic.phtml');
?>
<script type="text/javascript" src="/js/bootstrap-editable.js"></script>
<!-- 表格工具 -->
<script src="/js/listUtils/index.js"></script>
<!-- 表格可编辑 -->
<script src="/js/listUtils/editAbleUtil.js"></script>
<!-- 表格批量操作 -->
<script src="/js/listUtils/batchOperation.js"></script>

<script>
    $(function () {
        $("[data-toggle='tooltip']").tooltip();
    });


    clientaccountAPI(function (result) {
        var req = JSON.parse(result);
        if (req.status == 1 && req.data != null) {
            $("#companyName").html(req.data.name);
        }
    });
    var addUrl = '/promotion/adcreativeaddview?planId=' + GetQueryString('planId') + '&groupId=' + GetQueryString('groupId') + '&entrance=creative';
    var editUrl = '/promotion/adcreativeeditview';
    var statusArry = {'active': '启用', 'pause': '暂停'};
    var purpose = {'landing': '落地页', 'download': '应用下载'};
    $("#plan_id").val(GetQueryString('planId'));

    var ListPageConfig = {
        tableId: '#table',   // 表格id
        tableIndexCol: 'id', //数据索引字段 一般为 uid 或者 id
        func: function (data) {
            $(".table-do-tips").bind("mouseenter", function () {
                layer.tips('修改创意物料，修改前的创意物料保持修改前的状态不能修改；修改后的创意物料审核通过后覆盖修改前创意物料。', $(this), {
                    tips: [1, '#353538'],
                    area: ['auto', 'auto']
                });
            });
            $(".table-do-tips").bind("mouseleave", function () {
                layer.closeAll();
            })
            $("[data-toggle='popover']").popover();
        },
        executeFilterBind: function () {//bootstrap-table中绑定tableFilter事件
            bindTableFilterAction('purpose');
            bindTableFilterAction('status');
        },
        url: {
            add: addUrl,         //新建广告创意
            copy_edit: editUrl,         //修改创意
            creativeStatus: '/promotion/adcreativeupdatestatus' //状态(有效/暂停)修改接口
        },
        api: {
            creativeStatus: adgroupupdatestatusAPI //修改状态接口
        },
        htmlConfig: {
//            preview:['<a class="preview" style="color: #3d5d9f;padding: 0 3px;cursor: pointer;">预览</a>'],
//            copy_edit: ['<a class="copy_edit" style="color: #3d5d9f;padding: 0 3px;cursor: pointer;">创意修改</a>'],
            copy_edit: ['<div class="copy_edit dl-list-action-btn-wrapper"  title="修改">',
                '<img src="../img/icon/icon_edit.png" class="dl-list-action-btn">',
                '</div>']

//            creativeStatusP: ['<a class="creativeStatus" style="color: #3d5d9f;padding: 0 3px;cursor: pointer;">暂停</a>'],
//            creativeStatusA: ['<a class="creativeStatus" style="color: #3d5d9f;padding: 0 3px;cursor: pointer;">有效</a>'],
        },
        operateEvents: {
            'click .preview': function (e, value, row, index) {
                layer.open({
                    type: 1,
                    title: '创意预览',
                    closeBtn: 0, //不显示关闭按钮
                    shadeClose: true, //开启遮罩关闭
                    area: ['320px', '568px'], //宽高
                    content: row.code
                });
            },
            'click .copy_edit': function (e, value, row, index) {
                window.location.href = ListPageConfig.url.copy_edit + '?planId=' + row.plan_id + '&groupId=' + row.goup_id + '&id=' + row.id;
            }
        },
        title: {
            addTitle: '添加用户权限',
            editTitle: '修改用户权限'
        },
        showDetail: false,         //是否显示详细信息按钮
        action: {
            preview: true,
            copy_edit: true,
            creativeStatus: true
        },
        toolbar: function () {
        },
        table: {//表格参数
            height: undefined,//定义表格的高度
            undefinedText: '-',//当数据为undefined时显示的字符
            striped: true,//设置为 true 会有隔行变色效果
            sortName: undefined,//定义排序列,通过url方式获取数据填写字段名，否则填写下标
            sortOrder: 'desc',//定义排序方式 'asc' 或者 'desc'
            sortStable: true,//设置为 true 将获得稳定的排序，我们会添加_position属性到 row 数据中。
            url: '/promotion/adcreativelist',//服务器数据的加载地址
            queryParams: function queryParams(params) {//请求服务器数据时，你可以通过重写参数的方式添加一些额外的参数
                var parent = $('#table').parent();
                parent.attr('data-scrollTop', parent.scrollTop());
                var loading = parent.find('.fixed-table-loading:first');
                loading.show();
                var searchDate = $('#searchDate').val().replace(' - ', ',').split(',');//查询日期
                params['begin'] = searchDate[0].replace(/\//g, '-');
                params['end'] = searchDate[1].replace(/\//g, '-');
                params['search'] = $("#searchKeyword").val();
                params['status'] = $("input[name=status]:checked").val();
                params['plan_id'] = $("#plan_id").val();
                $('.detail_pop').popover('hide');
                return params;
            },
            onLoadSuccess: function(res){
                var parent = $('#table').parent();
                var top = parent.attr('data-scrollTop') || 0;
                parent.scrollTop(top);
                positionTableHeader();
            },
            responseHandler: function (res) {//加载服务器数据之前的处理程序，可以用来格式化数据。
                console.log(res)
                var loading = $('#table').parent().find('.fixed-table-loading:first');
                loading.hide();
                if (res.status == 1) {
                    if(res.data.group_id){
                        $("#adgroupName").html(res.data.group_name).removeClass('hidden')
                                .prev().removeClass('hidden');
                        $("#adplanName").html(res.data.plan_name).removeClass('hidden')
                                .prev().removeClass('hidden');
                    }
                    return res.data;
                } else {
                    console.log("格式化数据失败");
                    return res;
                }
            },
            toolbar: '#toolbar',//一个jQuery 选择器，指明自定义的toolbar 例如:#toolbar, .toolbar.
            searchAlign: 'left',
            pagination: true,//	设置为 true 会在表格底部显示分页条
            paginationLoop: true,//	设置为 true 启用分页条无限循环的功能。
            onlyInfoPagination: false,//设置为 true 只显示总数据数，而不显示分页按钮。需要 pagination='True'
            sidePagination: 'server',//设置在哪里进行分页，可选值为 'client' 或者 'server'。设置 'server'时，必须设置 服务器数据地址（url）或者重写ajax方法
            pageNumber: 1,//如果设置了分页，首页页码
            pageSize: 50,  //如果设置了分页，页面数据条数
            pageList: [30, 50, 100],//如果设置了分页，设置可供选择的页面数据条数。设置为All 则显示所有记录。
            search: false,//是否启用搜索框
            showFooter: false,//是否显示列脚
            showColumns: true,//是否显示 内容列下拉框
            showRefresh: true,//是否显示 刷新按钮
            showToggle: false,//是否显示 切换试图（table/card）按钮
            showPaginationSwitch: false,//是否显示 数据条数选择框
            paginationVAlign: 'bottom',//指定 分页条 在垂直方向的位置。'top' or 'bottom' or 'bonth'
            paginationPreText: '上一页',//指定分页条中上一页按钮的图标或文字
            paginationNextText: '下一页',//指定分页条中下一页按钮的图标或文字
            clickToSelect: false,//设置true 将在点击行时，自动选择rediobox 和 checkbox
            singleSelect: false,//设置True 将禁止多选
            checkboxHeader: true,//设置false 将在列头隐藏check-all checkbox
            maintainSelected: false,//设置为 true 在点击分页按钮或搜索按钮时，将记住checkbox的选择项
            sortable: true,//设置为false 将禁止所有列的排序
            silentSort: true,//设置为 false 将在点击分页按钮时，自动记住排序项。仅在 sidePagination设置为 server时生效.
            cookie: true,
            cookieIdTable: 'replacebyListJS', cookiesEnabled: ['bs.table.pageNumber'],
            cookiePath: '/',
            rowStyle: function (row, index) {//自定义行样式 参数为：row: 行数据 index: 行下标 返回值可以为class或者css
                return {};
//                if ((index % 2) !== 0) {//demo
//                    return {
//                        css: {'color': 'red'}
//                    }
//                }else{
//                    return{}
//                }
            },
            rowAttributes: function rowAttributes(row, index) {//自定义行属性 参数为：row: 行数据 index: 行下标 返回值可以为class或者css 支持所有自定义属性
                return {
//                    'data-id': row.guid,
//                    'data-htmlpath': row.htmlPath,
//                    'data-xmlpath': row.xmlPath
                }
            },
            onMouseoverRow: function (row, $element) {//自定义行鼠标覆盖事件
                $element.find('.status_modify').css('display', 'inline-block');
            },
            onMouseoutRow: function (row, $element) {//自定义行鼠标移出事件
                $element.find('.status_modify').css('display', 'none');
            },
//            onRefresh: function (params) {
//                console.log('1212121212');
//                return params;
//            },
            columns: [{//列参数
                checkbox: true
            }, {
                field: 'name',
                title: '创意名',
                formatter: function (value, row, index) {
                    return '<span class="cutValue">' + cutstrbyChar(value, 16) + '</span>' + tableEditTemplate.content;
                },
                events: Object.assign({
                    'mouseenter .cutValue': function (e, value, row, index) {
                        if (getCharLength(value) > 16) {
                            layer.tips(value, e.target, {
                                tips: [1, '#353538'],
                                area: ['auto', 'auto']
                            });
                        }
                    },
                    'mouseleave .cutValue': function (e, value, row, index) {
                        if (getCharLength(value) > 16) {
                            layer.closeAll()
                        }
                    },
                },
                //修改创意名称
                tableEditTemplate.getEvents({
                    validate: 'charSize',
                    min: 1, max: 50,
                    msg: '名称不能为空！50个字以内',
                    url: '/adcreative/update',
                    query: function(data){
                        return {
                            type: 'name',
                            id: data.id,
                            name: data.value,
                        }
                    }
                }))
            // }, {
            //    field: 'code',
            //    title: '创意缩略图'
            }, {
                field: 'material',
                title: '创意标题',
                formatter: function (value, row, index) {
                    var title = value.title;
                    if(title === undefined){
                        return;
                    }
                    return '<span class="cutValue">' + cutstrbyChar(title, 16) + '</span>' + tableEditTemplate.content;
                },
                events: Object.assign({
                    'mouseenter .cutValue': function (e, value, row, index) {
                        if (getCharLength(value.title) > 16) {
                            layer.tips(value.title, e.target, {
                                tips: [1, '#353538'],
                                area: ['auto', 'auto']
                            });
                        }
                    },
                    'mouseleave .cutValue': function (e, value, row, index) {
                        if (getCharLength(value.title) > 16) {
                            layer.closeAll()
                        }
                    },
                },
                //修改创意标题
                tableEditTemplate.getEvents({
                    field: 'title',
                    validate: 'size',
                    min: 2, max: 23,
                    msg: '创意标题不能为空！2-23个字',
                    url: '/adcreative/update',
                    query: function(data){
                        return {
                            type: 'material',
                            id: data.id,
                            material: {
                                title: data.value,
                            }
                        }
                    }
                }))
            }, {
                field: 'material',
                title: '图片预览',
                formatter: function (value, row, index) {
                    if(value.pic){
                        return '<img style="width: 80px;" src="//static.adm.deepleaper.com/material/' + value.pic + '"/>'
                    }else if(value.pic1){
                        return `<div style="width: 160px;">
                            <img style="width: 50px;" src="//static.adm.deepleaper.com/material/${value.pic1}"/>
                            <img style="width: 50px;" src="//static.adm.deepleaper.com/material/${value.pic2}"/>
                            <img style="width: 50px;" src="//static.adm.deepleaper.com/material/${value.pic3}"/>
                        </div>`
                    }
                }
            }, {
                field: 'link',
                title: 'URL',
                width: '100px',
                formatter: function (value, row, index) {
                    return '<span class="cutValue">' + cutstrbyChar(value, 16) + '</span>' + tableEditTemplate.content;
                },
                events: Object.assign({
                    'mouseenter .cutValue': function (e, value, row, index) {
                        if (getCharLength(value) > 16) {
                            layer.tips(value, e.target, {
                                tips: [1, '#353538'],
                                area: ['auto', 'auto']
                            });
                        }
                    },
                    'mouseleave .cutValue': function (e, value, row, index) {
                        if (getCharLength(value) > 16) {
                            layer.closeAll()
                        }
                    },
                },
                //修改创意URL
                tableEditTemplate.getEvents({
                    validate: 'url',
                    msg: '请填写以http://，https://开头的有效着陆页！',
                    url: '/adcreative/update',
                    query: function(data){
                        return {
                            type: 'url',
                            id: data.id,
                            url: {
                                link: data.value,
                            }
                        }
                    }
                }))
            }, {
                    field: 'status',
                    title: '状态' + jointTableFilter('status', statusArry),
                    formatter: function (value, row, index) {
                        switch (value) {
                            case 'pause':
                                return '<span style="color: #fd998c;position: relative;top: 2px;margin-right: 5px;">暂停</span><img class="status_modify status_start" src="../img/icon/icon_start.png" title="启用">';
                                break;
                            case 'active':
                                return '<span style="color: #00d5cd;position: relative;top: 2px;margin-right: 5px;">启用</span><img class="status_modify status_pause" src="../img/icon/icon_pause.png" title="暂停">';
                                break;
                            default:
                                return value;
                        }
                    },
                    events: {
                        'click .status_modify': function (e, value, row, index) {//status开关
                            if ('active' == row.status) {
                                row.status = 'pause';
                            } else {
                                row.status = 'active';
                            }
                            var postData = {
                                'ids': row.id,
                                'status': row.status
                            };
                            ListPageConfig.api.creativeStatus(ListPageConfig.url.creativeStatus, postData, function (result) {
                                var req = JSON.parse(result);
                                if (req.status == 1) {
                                    $(ListPageConfig.tableId).bootstrapTable('refresh', {silent: true});
                                } else {
                                    Comm.error(data.msg);
                                }
                            });
                        }
                    },
                    width: '85px'
                }, {
                    field: 'plan_name',
                    title: '广告计划',
                    formatter: function (value, row, index) {
                        return '<a class="planname" style="color: #3d5d9f;cursor: pointer;"><span class="cutValue">' + cutstrbyChar(value, 16) + '</span></a>';
                    },
                    events: {
                        'mouseenter .cutValue': function (e, value, row, index) {
                            if (getCharLength(value) > 16) {
                                layer.tips(value, e.target, {
                                    tips: [1, '#353538'],
                                    area: ['auto', 'auto']
                                });
                            }
                        },
                        'mouseleave .cutValue': function (e, value, row, index) {
                            if (getCharLength(value) > 16) {
                                layer.closeAll()
                            }
                        },
                        'click .planname': function (e, value, row, index) {
                            window.location.href = '/promotion/adcreativelistview?planId=' + row.plan_id + '&groupId=' + row.goup_id;
                        },
                    }
                }, {
                    field: 'goup_name',
                    title: '广告组',
                    formatter: function (value, row, index) {
                        return '<a class="planname" style="color: #3d5d9f;cursor: pointer;"><span class="cutValue">' + cutstrbyChar(value, 16) + '</span></a>';
                    },
                    events: {
                        'mouseenter .cutValue': function (e, value, row, index) {
                            if (getCharLength(value) > 16) {
                                layer.tips(value, e.target, {
                                    tips: [1, '#353538'],
                                    area: ['auto', 'auto']
                                });
                            }
                        },
                        'mouseleave .cutValue': function (e, value, row, index) {
                            if (getCharLength(value) > 16) {
                                layer.closeAll()
                            }
                        },
                        'click .planname': function (e, value, row, index) {
                            window.location.href = '/promotion/adplanlistview?groupId=' + row.goup_id;;
                        },
                    }
                }, {
                    field: 'audit_status',
                    title: 'Deepleaper审核状态',
                    sortable: true,
                    formatter: function (value, row, index) {
                        switch (value) {
                            case 'audit':
                                return '<i class="icon-question-sign " style="margin-right: 2px;cursor: pointer;"></i>审核中';
                                break;
                            case 'reject':
                                return '<i class="icon-remove-sign " style="margin-right: 2px;cursor: pointer;"></i>审核拒绝 <br/><span class="aduit_reject" style="color: lightgrey; margin-left: 12px;">拒绝原因</span>';
                                break;
                            case 'pass':
                                return '<i class="icon-ok-sign " style="margin-right: 2px;cursor: pointer;"></i>审核通过';
                                break;
                            default:
                                return value;
                        }
                    },
                    events: {
                        'mouseenter .aduit_reject': function (e, value, row, index) {
                            if (row.comment) {
                                layer.tips("<span style='color:black'>" + row.comment + "</span>", e.target, {
                                    tips: [3, '#fff'],
                                    area: ['auto', 'auto']
                                });
                            } else {
                                layer.tips("<span style='color:black'>" + '获取审核拒绝原因失败' + "</span>", e.target, {
                                    tips: [3, '#fff'],
                                    area: ['auto', 'auto']
                                });
                            }
                        },
                        'mouseleave .aduit_reject': function (e, value, row, index) {
                            if (row.comment) {
                                layer.closeAll()
                            }
                        }
                    }
                },
                {
                    field: 'audit_others',
                    title: '媒体审核状态',
                    sortable: true,
                    formatter: function (value, row, index) {
                        var length = 0;
                        length = value.length;
                        if(length == 0){
                            return '-';
                        }else{
                            return '<a class="detail_pop"  ishide_id=' + row.id  + '  style="cursor: pointer;text-decoration: underline; border: 0px" data-container="body" data-toggle="popover" data-placement="bottom" data-html="true" data-content=""> 详情 </a>';
                        }
                    },
                    events: {
                        'click .detail_pop': function (e, value, row, index) {
                                $('.detail_pop').popover('hide');
                                    if (value.length == 0) {
                                        $('a[ishide_id=' + row.id + ']').popover('hide');
                                    }
                                    else{
                                        setTimeout(function () {
                                            $('a[ishide_id=' + row.id + ']').popover('show');
                                            $(".detail_pop").attr('data-content', '');
                                        }, 0)
                                        var html = '<div class="list_close" ><img src="/img/list_close.png" onclick="fun_close(' + row.id + ')"></div>';
                                        html += '<div class="list_container">';
                                        for (var i = 0; i < value.length; i++) {
                                            html += '<div class="list_line" onmouseover="mouseover_color('+ row.id + ',' + i + ')" onmouseout="mouseout_color('+ row.id + ',' + i + ')"> <div class="list_left" change_color_id="'+ row.id + i +'" >' + value[i].name + '</div> <div class="list_right" change_color_id="'+ row.id + i +'">' + trans_status(value[i].audit_status, value[i].comment, i) + '</div> </div>';
                                        }
                                        html += '</div>'
                                        $(".detail_pop").attr('data-content', html);
                                    }

                            function trans_status(audit_status, comments, i) {
                                switch (audit_status) {
                                    case 'audit':
                                        return '<i class="icon-question-sign " style="margin-right: 2px;cursor: pointer;"></i>审核中';
                                        break;
                                    case 'reject':
                                        return '<i class="icon-remove-sign " style="margin-right: 2px;cursor: pointer;"></i>审核拒绝 <a class="aduit_detail_reject"  other_reason_id= "'+ row.id + i +'" other_reason ="'+ comments +'" style="color: lightgrey; margin-left: 6px;" onmouseover="mouse_over('+ row.id + ',' + i + ')" onmouseout="mouseOut('+ row.id + ',' + i + ')">原因</a>';
                                        break;
                                    case 'pass':
                                        return '<i class="icon-ok-sign " style="margin-right: 2px;cursor: pointer;"></i>审核通过';
                                        break;
                                    case 'wait':
                                        return '<i class="icon-question-sign " style="margin-right: 2px;cursor: pointer;"></i>待审核';
                                    default:
                                        return audit_status;
                                }
                            }
                        }
                    }
                },
                {
                    field: 'spend_budget',
                    title: '花费(元)'

                }, {
                    field: 'imp',
                    title: '展示数'

                }, {
                    field: 'clk',
                    title: '点击数'

                }, {
                    field: 'ctr',
                    title: '点击率',
                    formatter: function (value, row, index) {
                        return value == null ? null : strToPercent(value);
                    }
                }, {
                    field: 'do',
                    title: '操作' + '<i class="icon-question-sign table-do-tips" style="margin:0 3px 0 2px;cursor: pointer;"></i>',
                    align: 'center',
                    formatter: 'List.operateFormatter',
                    events: 'List.operateEvents',
                    width: '100px'
                }]
        }
    };
    initdaterangepicker($("#searchDate"), moment(), moment(), moment(), moment('1970-01-01'));
    $("#companyName").bind('click', function () {
        window.location.href = '/promotion/adgrouplistview';
    });
    $("#adgroupName").bind('click', function () {
        window.location.href = '/promotion/adplanlistview?planId=' + GetQueryString('planId') + '&groupId=' + GetQueryString('groupId');
    });
    var auth = getAuthorityByUrl('/promotion/adgrouplistview');
    function checkAuthority() {
        if (auth == 0) {
            ListPageConfig.action = {
                preview: true,
                copy_edit: false
            };
            toFirstLegalPage();
        } else if (auth == 1) {
            ListPageConfig.action = {
                preview: true,
                copy_edit: false
            };
        } else if (auth == 2) {
            ListPageConfig.action = {
                preview: true,
                copy_edit: true
            };
        }
    }
    checkAuthority();
    hideChangeBtnIfNeed(auth);
</script>

<script type="text/javascript">

    function fun_close(obj) {
        $('a[ishide_id=' + obj + ']').popover('hide');
    }

    function mouse_over(obj, i) {
        var  comments = $('a[other_reason_id=' + obj + i + ']').attr('other_reason');
        if (comments) {
            layer.tips("<span style='color:black'>" + comments + "</span>", $('a[other_reason_id=' + obj + i  + ']') , {
                tips: [3, '#fff'],
                area: ['auto', 'auto']
            });

        }
    }

    function mouseOut(obj,i) {
        layer.closeAll()
    }

    function mouseover_color(obj, i) {
        $('div[change_color_id=' + obj + i + ']').css('background-color','#f6f6f6');
    }
    function mouseout_color(obj, i) {
        $('div[change_color_id=' + obj + i + ']').css('background-color','#ffffff');
    }

</script>

<!-- 批量操作开始 -->
<script>
    /* 批量启用，暂停，删除操作 **/
    initBatchUpdateStatus({
        id: 'all-update',
        name: '广告创意',
        url: '/adcreative/batchUpdate',
    });

    /* 批量修改创意标题/描述 **/
    initBatchUpdateOperation({
        id: 'all-title',
        name: '广告创意',
        title: '修改创意标题/描述（已选择#length个广告创意）',
        url: '/adcreative/batchUpdate',
        init: function(parent){
            parent.find('.modal-body textarea').val('');
        },
        query: function(parent, dataIds){
            var inputTitle = parent.find('.modal-body textarea').eq(0);
            var inputDes = parent.find('.modal-body textarea').eq(1);
            var title = inputTitle.val();
            var description = inputDes.val();
            if(!(title || description)){
                layer.msg('请至少输入一项！');
                inputTitle.focus();
                return false;
            }
            if(!validateString(title, 'sizeIsNull', 2, 23)){
                layer.msg('创意标题格式错误！2-23个字');
                inputTitle.focus();
                return false;
            }
            if(!validateString(description, 'sizeIsNull', 2, 23)){
                layer.msg('创意描述格式错误！2-23个字');
                inputDes.focus();
                return false;
            }
            return {
                type: 'material',
                ids: dataIds,
                material:{
                    title: title,
                    description: description,
                }
            }
        },
    });

    /* 批量修改创意URL **/
    initBatchUpdateOperation({
        id: 'all-url',
        name: '广告创意',
        title: '修改创意URL（已选择#length个广告创意）',
        url: '/adcreative/batchUpdate',
        init: function(parent){
            parent.find('.modal-body input').val('');
        },
        query: function(parent, dataIds){
            var inputLink = $('#all-url-modal .modal-body input').eq(0);
            var inputMonitoring = $('#all-url-modal .modal-body input').eq(1);
            var inputLanding = $('#all-url-modal .modal-body input').eq(2);
            var link = inputLink.val();
            var monitoring = inputMonitoring.val();
            var landing = inputLanding.val();
            if(!(link || monitoring || landing)){
                layer.msg('请至少输入一项！');
                inputLink.focus();
                return false;
            }
            if(!validateString(link, 'urlIsNull')){
                layer.msg('请填写以http(https)开头的有效着陆页！');
                inputLink.focus();
                return false;
            }
            if(!validateString(monitoring, 'urlIsNull')){
                layer.msg('请填写以http(https)开头的有效第三方曝光监测链接！');
                inputMonitoring.focus();
                return false;
            }
            if(!validateString(landing, 'urlIsNull')){
                layer.msg('请填写以http(https)开头的有效第三方点击监测链接！');
                inputLanding.focus();
                return false;
            }
            return {
                type: 'url',
                ids: dataIds,
                url:{
                    link: link,
                    monitoring_url: monitoring,
                    landing: landing,
                }
            }
        },
    });
    
    /* 打开批量复制 **/
    initBatchUpdateOperation({
        id: 'all-copy',
        name: '广告创意',
        title: '复制广告创意（已选择#length个广告创意）',
        url: '/adcreative/batchCopy',
        init: function(parent){
            getPlans4copy();
            parent.find('.modal-body input:first').selected();
        },
        query: function(parent, dataIds){
            var planIds = [].slice.call(
                parent.find('.modal-body input[type=checkbox]:checked')
            ).map(t=>$(t).val());
            if(!planIds.length){
                layer.msg('请选择广告创意！');
                return false;
            }
            return {
                cid: dataIds,
                pid: planIds,
            }
        },
        success: function(parent, param){
            var t = parent.find('.modal-body input[type=checkbox]:checked:first');
            var planId = t.val();
            var groupId = t.attr('data-group');
            window.location.href = '/promotion/adcreativelistview?planId=' + planId + '&groupId=' + groupId;
        },
    });

    /* 打开新建 **/
    $('#add-new-open').on('click', function(){
        var planId = GetQueryString('planId');
        var groupId = GetQueryString('groupId');
        if(planId === null){
            getPlans4new();
            $('#add-new-modal .modal-body .data-search input').val('');
            $('#add-new-modal').modal('show');
            return;
        }
        window.location.href = '/promotion/adcreativeaddview?planId=' + planId + '&groupId=' + groupId + '&entrance=creative';
    });
    
    /* 新建广告组 **/
    $('#add-new').on('click', function(){
        var selected = $('#add-new-modal .modal-body .data-main input:checked');
        var planId = selected.val();
        var groupId = selected.attr('data-group');
        if(!planId){
            layer.msg('请选择广告计划！');
            return;
        }
        window.location.href = '/promotion/adcreativeaddview?planId=' + planId + '&groupId=' + groupId + '&entrance=creative';
    });

    /* 新建时查找广告组 **/
    $('#add-new-modal .modal-body .data-search div').on('click', function(){
        var search = $('#add-new-modal .modal-body .data-search input').val();
        getPlans4new(search);
    });

    /* 复制时查找广告组 **/
    $('#add-copy-modal .modal-body .data-search div').on('click', function(){
        var search = $('#add-copy-modal .modal-body .data-search input').val();
        getPlans4copy(search);
    });

    /* 获取广告计划 **/
    function getPlans(data, callback){
        var url = '/adgroup/groups';
        http_post_data(url, 'get', {
            plan: 1,
            search: data.search || '',
        }, function(res){
            if(1 === res.status){
                callback && callback(res.data);
            }else{
                layer.msg(res.msg);
            }
        });
    }

    /* 新建获取广告计划 **/
    function getPlans4new(search){
        getPlans({search, search}, function(data){
            $('#add-new-modal .modal-body .data-main').html(
                data.map(function(t, index){
                    var groupId = t.group_id;
                    var groupName = t.group_name.replace(/</g, '&lt;');
                    return `<div style="display: table-row;">
                        <div style="display: table-cell;">
                            <details ${index === 0 ? 'open' : ''} title="${groupName}">
                                <summary style="height: 18px;">
                                    <p style="height: 18px;position: relative;top: -17px;left: 12px;max-width: 300px;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">
                                        ${groupName}
                                    </p>
                                </summary>
                                ${t.child ? t.child.map(function(c, i){
                                    var planName = c.plan_name.replace(/</g, '&lt;');
                                    return `<div class="input-group" style="display: block;max-width: 300px;overflow: hidden;text-overflow: ellipsis;">
                                        <label class="radio-inline" style="white-space: nowrap;" title="${planName}">
                                            <input type="radio" data-group="${groupId}" value="${c.plan_id}" ${
                                                    index === 0 && i === 0 ? 'checked="checked"' : ''
                                            } name="add-new-modal-radio" style="margin-top: 0;"/>
                                            ${planName}
                                        </label>
                                    </div>`
                                }).join('') : ''}
                            </details>
                        </div>
                        <div style="height: 18px;display: table-cell;padding-left: 50px;">${purpose[t.purpose] || t.purpose}</div>
                    </div>`
                }).join('')
            );
        });
    };

    /* 复制获取广告计划 **/
    function getPlans4copy(search){
        getPlans({search, search}, function(data){
            $('#all-copy-modal .modal-body .data-main').html(
                data.map(function(t, index){
                    var groupId = t.group_id;
                    return `<div style="display: table-row;">
                        <div style="display: table-cell;" class="selected">
                            <details ${index === 0 ? 'open' : ''}>
                                <summary>${t.group_name.replace(/</g, '&lt;')}</summary>
                                ${t.child ? t.child.map(function(c, i){
                                    return `<div class="input-group">
                                        <label style="font-weight: 400;">
                                            <input type="checkbox" data-group="${groupId}" value="${c.plan_id}"></input>
                                            <span>${c.plan_name.replace(/</g, '&lt;')}<span>
                                        </label>
                                    </div>`
                                }).join('') : ''}
                            </details>
                        </div>
                        <div style="display: table-cell;padding-left: 50px;">${purpose[t.purpose] || t.purpose}</div>
                    </div>`
                }).join('')
            );
        });
    };
</script>
<!-- 批量操作结束 -->

<style type="text/css">

    /*弹出框的大小*/
    .popover.bottom {
        margin-top: 10px;
        width: 260px;
        height: 240px;
        margin-left: 118px;
        background-color: #f6f6f6;
        border: 1px solid #e9e9e9;
        z-index: 999;
    }

    .popover > .arrow, .popover > .arrow:after {
        position: absolute;
        display: none;
        width: 0;
        height: 0;
        border-color: transparent;
        border-style: solid;
    }
    .list_close {
        width: 240px;
        height: 20px;
        text-align: right;
        padding-right: 10px;
    }

    .list_close img {
        cursor: pointer;
    }

    .list_container {
        width: 230px;
        height: 190px;
        background-color: #FFFFFF;
        overflow-y: scroll;
        overflow-x: hidden;
    }

    .list_left, .list_right {
        width: 110px;
        text-align: left;
        display: inline-block;
        float: left;
        padding-left: 5px;
    }
    .list_left{
        width: 120px;
    }
    .list_right{
        padding-left: 10px;
    }
    .list_line{
        width: 230px;
        height: 30px;
        line-height: 30px;
    }


</style>


<?php
echo $this->renderFile('@app/views/layouts/listAd.phtml');
?>
