<link rel="stylesheet" href="../css/Dl_normalize.css"/>
<?php
echo $this->renderFile('@app/views/layouts/formPublicHeader.phtml');
?>
<div class="user-message-list">
    <div class="user-message-list-name">
        <ol>
            <li>
                <span id="companyName" class="user-message-name linkable"><a href="/promotion/adgrouplistview">广告组列表</a></span>
                <img class="separator" src="/img/arrow.png">
                <span id="adgroupName" class="user-message-name">修改广告组</span>
            </li>
        </ol>
    </div>
</div>
<div class="Dl-fullscreen-line"></div>
<input type="hidden" name="group_id" id="group_id">
<div style="margin-top: 30px">
    <form class="form-horizontal" role="form">
        <div class="form-group ">
            <label class="col-md-2 col-md-offset-1 control-label Dl-required">广告组名称</label>
            <div class="col-md-7">
                <input type="text" class="form-control" value="" id="name">
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="form-group ">
            <label class="col-md-2 col-md-offset-1 control-label Dl-required">选择推广目的</label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="purpose" disabled>
                    <option value="landing">落地页</option>
                    <option value="download">应用下载</option>
                </select>
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="form-group ">
            <label class="col-md-2 col-md-offset-1 control-label Dl-required">日预算</label>
            <div class="col-md-7">
                <input type="text" class="form-control" value="" id="budget" placeholder="可输入金额范围：50~9999999999.99">
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="row submit_box">
            <div class="submit_btn_wrapper">
                <div class="submit_btn" id="cancel">
                    返回列表
                </div>
                <div class="submit_btn submit_btn_default submit_btn_active" id="submit">
                    保存修改
                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        checkActionAuth('/promotion/adgrouplistview', 2);
        fetchadgroupAPI(GetQueryString('id'), fetchadgroupAPIonSuccessFun);
        function fetchadgroupAPIonSuccessFun(result) {
            var req = JSON.parse(result);
            if (req.status == 1) {
                var data = req.data;
                $("#name").val(data.name);
                $("#budget").val(data.budget);
                $("#purpose option[value=" + data.purpose + "]").prop('selected', 'selected');
            } else {
                layer.msg(req.msg);
            }
        }

        var checkList = [
            {
                id: '#name',
                validationFunc: [vaIsNotNull, vaWordNumberLimit1_25],
                msg: ['广告组名称不能为空', '名称长度应为1-50个字符:汉字占2个字符']
            }, {
                id: '#budget',
                validationFunc: [vaIsMoneyFrom50NotNull],
                msg: ['日预算不能为空，且应为正确金额格式，可输入范围：50~9999999999.99']
            }
        ];
        for (var i = 0; i < checkList.length; i++) {
            var obj = checkList[i];
            $(obj.id).bind('blur', {obj: obj}, function (event) {
                return validatefun(event.data.obj);
            });
        }
        function validatefun(obj) {
            for (var i = 0; i < obj.validationFunc.length; i++) {
                if (!obj.validationFunc[i]($(obj.id).val())) {
                    vaError($(obj.id), obj.msg[i]);
                    return false;
                } else {
                    vaSuccess($(obj.id));
                }
            }
            return true;
        }

        function presubmit() {//提交验证
            for (var i = 0; i < checkList.length; i++) {
                var obj = checkList[i];
                if (!validatefun(obj)) {
                    return false;
                }
            }
            return true;
        }

        $('#submit').click(function () {
            $("#Deepleaper_loading").show();
            if (!presubmit()) {
                $("#Deepleaper_loading").hide();
                return false;
            }
            var id = GetQueryString('id');
            var name = $("#name").val();
            var purpose = $("#purpose").val();
            var budget = $("#budget").val();
            adgroupsaveeditAPI(id, name, purpose, budget, function (result) {
                var req = JSON.parse(result);
                console.log(req);
                if (req.status == 1) {
                    $("#Deepleaper_loading").hide();
                    layer.msg("广告组修改成功");
                    setTimeout(function () {
                        window.location = '/promotion/adgrouplistview'
                    }, 1000)
                } else {
                    $("#Deepleaper_loading").hide();
                    layer.msg(req.msg);
                }
            });
        });
        $("#cancel").bind('click', function () {
            window.location = '/promotion/adgrouplistview';
        })
    });
</script>
<?php
echo $this->renderFile('@app/views/layouts/formPublicFooter.phtml');
?>
