<link rel="stylesheet" href="/css/datepicker.css"/>
<link rel="stylesheet" href="../css/Dl_normalize.css"/>
<?php
echo $this->renderFile('@app/views/layouts/formPublicHeader.phtml');
?>
<link rel="stylesheet" href="/css/application/promotion/servicetime.css?v=20171129">
<link rel="stylesheet" href="/css/application/promotion/adplandirectionreuse.css?v=20171129">
<link rel="stylesheet" href="/css/application/promotion/adplan_mediaAdOrientation.css">

<link rel="stylesheet" href="/css/dlMultiMenu.css?v=20170814">
<link rel="stylesheet" href="/css/targetingadd.css?v=20170315">
<link rel="stylesheet" href="/css/DL-keyword.css?v=20170605">

<?php
echo $this->renderFile('@app/views/layouts/tablePublic.phtml');
?>
<div class="user-message-list">
    <div class="user-message-list-name">
        <ol>
            <li>
                <span id="companyName" class="user-message-name linkable"><a
                        href="/promotion/adgrouplistview"></a></span>
                <img class="separator" src="/img/arrow.png">
                <span id="adgroupName" class="user-message-name linkable"><a href="#"></a></span>
                <img class="separator" src="/img/arrow.png">
                <span class="user-message-name">添加广告计划</span>
            </li>
        </ol>
    </div>
</div>
<div class="Dl-fullscreen-line"></div>
<div style="margin-top: 30px">
    <form class="form-horizontal" role="form">
        <div class="form-group">
            <label class="col-md-2 col-md-offset-1 control-label ">广告组名称</label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="groupname" data-size="8">
                </select>
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="form-group">
            <label class="col-md-2 col-md-offset-1  control-label Dl-required">广告计划名称</label>
            <div class="col-md-7">
                <input type="text" class="form-control dl-notNull" id="planName">
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div id="setDownload" style="display: none">
                <div class="row Dl-part-title">
                    <div class="col-md-10 col-md-offset-1">
                        <span class="identifier">设置下载链接</span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 col-md-offset-1 control-label ">平台</label>
                    <div class="col-md-7">
                        <select class="selectpicker" data-width="100%" id="platCheck-download">
                            <option value="android">android</option>
                            <option value="ios">ios</option>
                        </select>
                    </div>
                    <span class="help-block col-md-7 col-md-offset-3"></span>
                </div>
                <div class="form-group">
                    <label class="col-md-2 col-md-offset-1  control-label Dl-required">下载链接</label>
                    <div class="col-md-7">
                        <input type="text" class="form-control dl-notNull" id="downloadLink">
                    </div>
                    <span class="help-block col-md-7 col-md-offset-3"></span>
                </div>
                <div class="form-group">
                    <label class="col-md-2 col-md-offset-1  control-label Dl-required">应用包名称</label>
                    <div class="col-md-7">
                        <input type="text" class="form-control dl-notNull" id="packageName">
                    </div>
                    <span class="help-block col-md-7 col-md-offset-3"></span>
                </div>
                <div class="form-group" id="appStore" style="display: none">
                    <label class="col-md-2 col-md-offset-1  control-label Dl-required">App Store ID</label>
                    <div class="col-md-7">
                        <input type="text" class="form-control dl-notNull" id="app-store-id">
                    </div>
                    <span class="help-block col-md-7 col-md-offset-3"></span>
                </div>
        </div>
        <div class="row Dl-part-title">
            <div class="col-md-10 col-md-offset-1">
                <span class="identifier">设置投放定向</span>
                <button class="btn btn-default direct-btn" id="direct-control-btn" type="button"
                        style="border-radius:4px;" data-toggle="modal"
                        data-target="#direct-container">复制已有定向设置</button>
            </div>
        </div>

        <div class="form-group ">
            <label class="col-md-2 col-md-offset-1  control-label">地域</label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="areaCheck">
                    <option value="0">不限</option>
                    <option value="1">省市</option>
                </select>
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="form-group" id="area-group" style="display: none">
            <label class="col-md-2 col-md-offset-1  control-label"></label>
            <div class="col-sm-6 " id="area-div">
                <select id="area" multiple="multiple">
                </select>
            </div>
        </div>
        <div class="form-group" id="platCheck-landing">
            <label class="col-md-2 col-md-offset-1 control-label ">平台</label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="platCheck">
                    <option value="0">不限</option>
                    <option value="1">自定义</option>
                </select>
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="form-group" id="plat-group" style="display: none">
            <label class="col-md-2 col-md-offset-1  control-label"></label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="customplatCheck" multiple title="落地页平台可多选">
                    <option value="ANDROID">android</option>
                    <option value="IOS">ios</option>
                </select>
            </div>
        </div>
        <div class="form-group ">
            <label class="col-md-2 col-md-offset-1 control-label ">网络</label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="networkCheck">
                    <option value="0">不限</option>
                    <option value="1">自定义</option>
                </select>
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="form-group" id="network-group" style="display: none">
            <label class="col-md-2 col-md-offset-1  control-label"></label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="customnetwork" multiple title="自定义网络可多选">
                    <option value="WIFI">WIFI</option>
                    <option value="4G">4G</option>
                    <option value="UNKNOWN">其他</option>
                </select>
            </div>
        </div>
        <div class="form-group" id="mediaWrapper">
            <label class="col-md-2 col-md-offset-1 control-label ">媒体广告位定向</label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="media">
                    <option value="0">不限</option>
                    <option value="1">自定义</option>
                </select>
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="form-group" id="media_ad_orientation" style="display: none ">
            <label class="col-md-2 col-md-offset-1  control-label">选择定向</label>
            <div class="col-md-7 ">
                <div id="dl_media" class=""></div>
            </div>
        </div>

        <div class="form-group keywords">
            <label class="col-md-2 col-md-offset-1 control-label">关键词设置</label>
            <div class="col-md-7 ">
                <div class="input-group">
                    <input id="keywordstatus" type="text" class="form-control dl-notNull" disabled
                           value="已有0个关键词，0个否定关键词">
                    <span class="input-group-btn">
                        <button class="btn btn-default" id="set_btn" type="button"
                                style="border-radius: 0 4px 4px 0;border-left: none;" data-toggle="modal"
                                data-target="#keywordModal">设置</button>
                    </span>
                    <div style="position: absolute;right: -310px;top: 9px; width: 300px;z-index:1;cursor: help">
                        <span id="KeywordsHint" class="glyphicon glyphicon glyphicon-question-sign"
                              data-container="body"
                              data-toggle="popover" data-placement="top" data-trigger="focus" title="关键词填写说明"
                              data-content="为了保证投放效果，填写的关键词需要与推广的产品相关联，并且保证计划下关键词数在1000个以内。"></span>
                    </div>
                </div>
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="form-group channelCheck">
            <label class="col-md-2 col-md-offset-1 control-label ">频道分类定向</label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="channelCheck">
                    <option value="0">不限</option>
                    <option value="1">自定义</option>
                </select>
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>

        <div class="form-group" id="channel-group" style="display: none">
            <label class="col-md-2 col-md-offset-1  control-label">选择定向</label>
            <div class="col-sm-6 " id="customchannel-div">
                <select id="customchannel" multiple="multiple">
                </select>
            </div>
        </div>

        <!--广告行为定向-->
        <div id="advertising-behavior-orientation"></div>
        <br />
        <!-- 用户兴趣标签定向 -->
        <div id="user-interest-label"></div>

        <div class="row Dl-part-title">
            <div class="col-md-10 col-md-offset-1">
                <span class="identifier">设置投放预算</span>
            </div>
        </div>

        <div class="form-group ">
            <label class="col-md-2 col-md-offset-1 control-label Dl-required" for="searchDate">投放周期</label>
            <div class="col-md-7">
                <input type="text" class="form-control" id="searchDate">
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>

        <div class="form-group channelCheck">
            <label class="col-md-2 col-md-offset-1 control-label ">投放时段</label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="serviceTime">
                    <option value="0">全天投放</option>
                    <option value="1">自定义投放时段</option>
                </select>
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>

        <div class="form-group" id="serviceTime-group" style="display: none">
            <label class="col-md-2 col-md-offset-1  control-label">选择投放时段</label>
            <div class="col-sm-6 ">
                <div id="serviceTimeSelected"></div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 col-md-offset-1  control-label Dl-required">日预算(元)</label>
            <div class="col-md-7">
                <input type="text" class="form-control" id="budget" placeholder="可输入金额范围：50~9999999999.99">
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="form-group ">
            <label class="col-md-2 col-md-offset-1 control-label Dl-required">计费方式</label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="bid_type">
                    <option value="cpm" selected>cpm(元/千次展示)</option>
                    <option value="cpc">cpc(元/次点击)</option>
                </select>
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="form-group">
            <label class="col-md-2 col-md-offset-1  control-label Dl-required">出价</label>
            <div class="col-md-7">
                <input type="text" class="form-control" id="price" placeholder="可输入金额范围：0.01~9999999999.99">
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
        <div class="row Dl-part-title">
            <div class="col-md-10 col-md-offset-1">
                <span class="identifier">高级设置</span>
            </div>
        </div>
        <div class="form-group ">
            <label class="col-md-2 col-md-offset-1 control-label">计划频次控制(次 / 每人每天)</label>
            <div class="col-md-7">
                <input type="text" class="form-control" id="frequency" placeholder="单个人每天最多看多少次广告 不填写时 频次没有上限">
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>

        <div class="form-group ">
            <label class="col-md-2 col-md-offset-1 control-label ">投放速度</label>
            <div class="col-md-7">
                <select class="selectpicker" data-width="100%" id="speed">
                    <option value="cs">匀速投放</option>
                    <option value="asap">快速投放</option>
                </select>
            </div>
            <span class="help-block col-md-7 col-md-offset-3"></span>
        </div>
</div>

<div class="row submit_box">
    <div class="submit_btn_wrapper">
        <div class="submit_btn" id="cancel">
            返回列表
        </div>
        <div class="submit_btn submit_btn_default submit_btn_active" id="submit">
            保存并继续
        </div>
    </div>
</div>

<!--设置关键词-->
<?php
echo $this->renderFile('@app/views/promotion/templatekeyword.phtml');
?>

<!-- 定向模态框（Modal） -->
<div class="modal fade" id="direct-container" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="margin-top: 200px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    复制已有定向设置
                </h4>
            </div>
            <div class="modal-body">
<!--                在这里添加一些文本-->
                <div class="directional-body">
                    <div class="directional-left">
                        <div class="directional-left-title">广告组>广告计划</div>
                        <div class="directional-left-body" id="directional-left-body"></div>
                    </div>
                    <div class="directional-right">
                        <div class="directional-right-title">定向设置</div>
                        <div class="directional-right-body" id="directional-right-body"></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-primary" id="save_btn">保存
                </button>
                <button type="button" class="btn btn-default" id="cancel_btn" data-dismiss="modal">关闭
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>

<?php
echo $this->renderFile('@app/views/layouts/formPublicFooter.phtml');
echo $this->renderFile('@app/views/layouts/bootstrapDaterangerpickerPublic.phtml');
?>
<script src="/js/bootstrap-editable.js" type="text/javascript"></script>
<script src="/js/application/promotion/adplan_targetingadd.js?v=20170512" type="text/javascript"></script>
<script src="/js/DL-keyword.js?v=20171212" type="text/javascript"></script>
<script src="/js/application/promotion/adplanservicetime.js?v=20171128"></script>
<script src="/js/application/promotion/adplandirectionreuse.js?v=20180401"></script>
<script src="/js/application/promotion/adplan_mediaAdOrientation.js"></script>
<script src="/js/application/promotion/adplanaddview.js?v=20180401" type="text/javascript"></script>
<script src="/js/utils/DLMultiMenu.js?v=20180401" type="text/javascript"></script>
