<?php
    echo $this->partial('layout/listPublicHeader.phtml');
?>
<script>

    var ListPageConfig = {
        tableId:'#table',   // 表格id
        func:function(data){
        },
        tableIndexCol :'uid', //数据索引字段 一般为 uid 或者 id
        table : {           //表格配置
             url: '/media/category',
            queryParams: 'queryParams',
            toolbar: '#toolbar',
            showColumns: true,
            searchAlign:'left',
            pagination: true,
            pageSize: 50,  //获取所有数据,建立二级结构
            sortOrder: 'desc',
            sidePagination: 'server',
            cookie: true,
            cookieIdTable: 'saveId',
            columns: [{
                checkbox: true
            }, {
                field: 'name',
                title: '媒体分类'
            },{
                field: 'info',
                title: '备注'
            }, {
                field: 'create_time',
                title: '创建时间',
                sortable:true,
           
            }, {
                field: 'do',
                title: '操作',
                align: 'center',
                formatter: 'List.operateFormatter',
                events: 'List.operateEvents',
            }]
        },
       url:{
            add         : '/media/categoryadd',         //添加 数据 html 地址
            edit        : '/media/categoryedit',         //编辑数据 html 地址
            del         : '/media/categorydel' ,         //删除数据地址
            detail      : false                      //详细内容地址,为空则取编辑的地址
        },
        title:{
            addTitle:'添加媒体分类',
            editTitle:'编辑媒体分类',
        },
       
    }
</script>


<?php
    echo $this->partial('layout/listPublicFooter.phtml');
?>