<?php
if ($this->item) {
    $name = $this->item['name'];
    $uid = $this->item['uid'];
    $info = $this->item['info'];
?>

<form id="edit" method="post" action="/media/categorysave"
	class="form-horizontal list-form"
	novalidate="novalidate">

	<div class="form-group ">

		<label class="col-sm-3 control-label">分类名称</label>
		<div class="col-sm-6 ">
			<input id="name" type="text" name="name" class="form-control"
				value="<?php echo $name;?>" check-type="required"
				required-message="不能为空。"> <input id="uid" type="hidden" name="uid"
				class="form-control" value="<?php echo $uid;?>">
		</div>
	</div>

	<div class="form-group ">
		<label class="col-sm-3 control-label">备注</label>
		<div class="col-sm-6 ">
			<input type="text" class="form-control" name="info" id="info"
				value="<?php echo $info;?>">
		</div>
	</div>
</form>
<?php }?>