<?php
echo $this->partial('layout/listPublicHeader2.phtml');
?>
<div class="user-message-list">
    <div class="user-message-list-name">
        <ol>
            <li>
                <span id="companyName" class="user-message-name linkable"><a href="/media/company">媒介渠道</a></span>
                <img class="separator" src="/img/arrow.png">
                <span id="adgroupName" class="user-message-name">添加媒介渠道</span>
            </li>
        </ol>
    </div>
</div>
<div class="Dl-fullscreen-line"></div>
<div style="width:100%;height:79px;padding-top: 10px">
    <?php if (isset($this->form['error'])) { ?>
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span
                    class="sr-only">Close</span></button>
            <strong>错误信息：</strong> <?php echo $this->form['error']; ?>
        </div>
    <?php } ?>
</div>
<form id="add" method="post" action="/media/companyadd" class="form-horizontal " novalidate="novalidate"
      onsubmit="return companyaddVilidate();">

    <div class="form-group">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">渠道名称:</label>
        <div class="col-sm-7">
            <input id="name" type="text" name="name" class="form-control"
                   value="<?php echo $this->form['name']; ?>" maxlength="50">
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>

    <div class="form-group ">
        <label class="col-md-2 col-md-offset-1 control-label">类型:</label>
        <div class="col-sm-7">
            <input type="radio" name="type" id="optionsRadios1"
                   value="agency" <?php if ($this->form['type'] == 'agency') echo 'checked="true"' ?>> &nbsp;&nbsp;媒介代理商
            &nbsp; &nbsp; &nbsp; &nbsp;
            <input type="radio" name="type" id="optionsRadios2"
                   value="staff" <?php if ($this->form['type'] == 'staff') echo 'checked="true"' ?>>&nbsp;&nbsp;直营媒体
        </div>
    </div>

    <div class="form-group ">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">联系人:</label>
        <div class="col-sm-7">
            <input type="text" class="form-control" name="linkman" id="linkman"
                   value="<?php echo $this->form['linkman']; ?>">
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>

    <div class="form-group ">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">联系人手机号码:</label>
        <div class="col-sm-7">
            <input type="text" class="form-control" name="tel" id="tel"
                   value="<?php echo $this->form['tel']; ?>">
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>

    <div class="row submit_box">
        <div class="submit_btn_wrapper">
            <div class="submit_btn" id="cancel">
                返回列表
            </div>
            <button type="submit" class="submit_btn submit_btn_default submit_btn_active" id="submit">
                完成添加
            </button>
        </div>
    </div>
</form>
<script>

    checkActionAuth('/media/company', 2);

    $(function () {
        var val = $('input:radio[name="type"]:checked').val();

        if (val == null) {

            $('#optionsRadios1').attr('checked', 'true');
        }


    });
    // 校验函数
    //校验规则：渠道不能空；手机号码可以空、校验格式；
    $('#name').blur(function () {
        if (!vaIsNotNull($(this).val())) {
            vaError($('#name'), '渠道名称不能为空');
        } else {
            vaSuccess($('#name'));
        }
    });
    $('#linkman').blur(function () {
        if (!vaIsNotNull($(this).val())) {
            vaError($('#linkman'), '联系人不能为空');
        } else {
            vaSuccess($('#linkman'));
        }
    });
    $('#tel').blur(function () {
        if (!vaIsNotNull($('#tel').val())) {
            vaError($('#tel'), '请输入联系人手机号码');
        } else if (!validatePhoneNum($('#tel').val())) {
            vaError($('#tel'), '手机号码格式错误');
        } else {
            vaSuccess($('#tel'));
        }
    });

    function companyaddVilidate() {
        $("#Deepleaper_loading").show();
        var name = $('#name');
        var nameVal = name.val();
        var linkman = $('#linkman');
        var linkmanVal = linkman.val();
        var tel = $('#tel');
        var telVal = tel.val();
        if (!vaIsNotNull(nameVal)) {
            $("#Deepleaper_loading").hide();
            vaError(name, '渠道名称不能为空');
            return false;
        } else if (!vaIsNotNull(linkmanVal)) {
            $("#Deepleaper_loading").hide();
            vaError(linkman, '联系人不能为空');
            return false;
        } else if (!vaIsNotNull(telVal)) {
            $("#Deepleaper_loading").hide();
            vaError(tel, '请输入联系人手机号码');
            return false;
        } else if (!validatePhoneNum(telVal)) {
            $("#Deepleaper_loading").hide();
            vaError(tel, '手机号码格式错误');
            return false;
        } else {
            $("#Deepleaper_loading").hide();
            return true;
        }
    }

    $("#cancel").bind('click', function () {
        window.location = '/media/company';
    });
</script>