
		<div class="container-fluid detail">
			<div class="row">
			  <div class="col-xs-11 col-md-11 col-lg-11 headimg">
                <div class="alt_menu">
                  <div class="sdk-type" id="ios_sdk">
                      <p class="p1 p1_active">iOS&nbsp;&nbsp;SDK下载</p>
                  </div>
                  <div class="sdk-type" id="android_sdk">
                      <p class="p2">Android&nbsp;&nbsp;SDK下载</p>
                  </div>
                    <div class="sdk-type" id="js_sdk">
                        <p class="p3">JS&nbsp;&nbsp;SDK下载</p>
                    </div>
                </div>
                <div class="type-detail" id="ios_container">
                    <div class="div2">
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">iOS&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">iOS&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">iOS&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">iOS&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                    </div>
                </div>
                <div class="type-detail" id="android_container">
                    <div class="div2">
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">Android&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">Android&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">Android&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">Android&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                    </div>
                </div>
                <div class="type-detail" id="js_container">
                    <div class="div2">
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">JS&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">JS&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">JS&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                        <div class="sdk-detail">
                            <div class="sdk-de">
                                <p class="p_title">JS&nbsp;&nbsp;SDK&nbsp;&nbsp;-&nbsp;&nbsp;开屏</p>
                                <p class="p_date">更新时间：2016-02-28</p>
                                <p class="p_version">版本号：3.2.1 </p>
                                <p class="p_link"><a>查看更新日志</a>&nbsp;&nbsp;<a>在线帮助文档</a></p>
                            </div>
                            <div class="dowenlo"><img src="../img/images/new_download.png"></div>
                        </div>
                    </div>
                </div>
              </div>
            </div>
        </div>
<script type="text/javascript">
    checkActionAuth('/media/download', 1);
</script>
<script type="text/javascript">
    $("#ios_sdk").bind('click', function () {
        $('.p1').addClass('p1_active');
        $('.p2').removeClass('p2_active');
        $('.p3').removeClass('p3_active');
        $("#android_container").fadeOut(100);
        $("#js_container").fadeOut(100);
        setTimeout(function () {
            $("#ios_container").fadeIn();
        }, 100)
    });
    $("#android_sdk").bind('click', function () {
        $('.p2').addClass('p2_active');
        $('.p1').removeClass('p1_active');
        $('.p3').removeClass('p3_active');
        $("#ios_container").fadeOut(100);
        $("#js_container").fadeOut(100);
        setTimeout(function () {
            $("#android_container").fadeIn();
        }, 100)
    });

    $("#js_sdk").bind('click', function () {
        $('.p3').addClass('p3_active');
        $('.p1').removeClass('p1_active');
        $('.p2').removeClass('p2_active');
        $("#ios_container").fadeOut(100);
        $("#android_container").fadeOut(100);
        setTimeout(function () {
            $("#js_container").fadeIn();
        }, 100)
    });
</script>