<?php
    echo $this->partial('layout/listPublicHeader.phtml');
?>
<style>
    .mw95 {min-width: 95px;}
</style>
<script>

    var ListPageConfig = {
        tableId:'#table',   // 表格id
        tableIndexCol :'uid', //数据索引字段 一般为 uid 或者 id
        table : {           //表格配置
            url: '/client/client',
            queryParams: 'queryParams',
            toolbar: '#toolbar',
            showColumns: true,
            searchAlign:'left',
            pagination: true,
            pageSize: 25,  //获取所有数据,建立二级结构
            sortOrder: 'desc',
            sidePagination: 'server',
            cookie: true,
            cookieIdTable: 'saveId',
            columns: [{
                checkbox: true
            }, {
                field: 'name',
                title: '广告主名'
            }, {
                field: 'url',
                title: '广告主URL'
            }, {
                field: 'category',
                title: '行业分类'
            }, {
                field: 'agency',
                title: '所属代理商'
            }, {
                field: 'commission',
                title: '服务费率'
            }, {
				field: 'duty_user',
				title: '负责人'
            }, {
                field: 'createUserName',
                title: '创建/修改人'
            }, {
                field: 'edit_time',
                title: '编辑时间'
            },{
                field: 'do',
                title: '操作',
                'class': 'mw95',
                align: 'center',
                formatter: 'List.operateFormatter',
                events: 'List.operateEvents'
            }]
        },
        url:{
            add         : '/client/clientadd',       //添加 数据 html 地址
            edit        : '/client/clientedit',      //编辑数据 html 地址
            del         : '/client/clientdel' ,      //删除数据地址
            detail      : false                      //详细内容地址,为空则取编辑的地址
        },
        title:{
            addTitle:'添加广告主',
            editTitle:'编辑广告主',
        },
        dialogWidth: 600,
        showDetail:false         //是否显示详细信息按钮
    }

</script>


<?php
    echo $this->partial('layout/listPublicFooter.phtml');
?>
