<?php
echo $this->partial('layout/listPublicHeader2.phtml');
//print_r($this->mediaclass_menu2);
// 	die;
?>
<div class="user-message-list">
    <div class="user-message-list-name">
        <ol>
            <li>
                <span id="companyName" class="user-message-name linkable"><a href="/media/media">媒体列表</a></span>
                <img class="separator" src="/img/arrow.png">
                <span id="adgroupName" class="user-message-name">修改媒体</span>
            </li>
        </ol>
    </div>
</div>
<div class="Dl-fullscreen-line"></div>

<form class="form-horizontal" role="form">

    <div class="form-group">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">媒体名称:</label>
        <div class="col-md-7">
            <input id="name" type="text" name="name" class="form-control" check-type="required" required-message="不能为空。"
                   value="<?php echo $this->form['name']; ?>">
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>

    <div class="form-group">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">媒体类型:</label>
        <div class="col-md-7">
            <label class="radio-inline">
                <input type="radio" name="type" value="2" id="type_web"
                       disabled <?php if ($this->form['type'] == 2) echo 'checked="checked"'; ?>>网页
            </label>
            <label class="radio-inline">
                <input type="radio" name="type" value="3" id="type_app"
                       disabled <?php if ($this->form['type'] == 3) echo 'checked="checked"'; ?>>应用
            </label>
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>

    <div class="form-group">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">媒体账户:</label>
        <div class="col-md-7">
            <select id="medium" name="medium" class="form-control selectpicker" data-live-search="true"
                    disabled="disabled ">
            </select>
            <!--            disabled="disabled-->
        </div>
    </div>

    <div class="form-group ">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">媒体所属分类:</label>
        <div class="col-md-7">
            <select id="selF" class="form-control selectpicker">
                <option>一级分类</option>
            </select>
        </div>
        <div class="col-md-7 col-md-offset-3" style="margin-top: 10px">
            <select id="selT" name="class" class="form-control selectpicker">
                <option>二级分类</option>
            </select>
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>

    <div class="form-group" id="url_group" style="display: none;">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">网站地址:</label>
        <div class="col-md-7">
            <input id="url" class="form-control" type="text" name="url" autocomplete="off"
                   value="<?php if ($this->form['type'] == 2) echo $this->form['bundle_id']; ?>">
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>

    <div class="form-group" id="bundle_id_group" style="display: none;">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">程序主包名:</label>
        <div class="col-md-7">
            <input id="bundle_id" class="form-control" type="text" name="bundle_id" disabled
                   value="<?php if ($this->form['type'] == 3) echo $this->form['bundle_id']; ?>">
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>

    <div class="form-group">
        <label class="col-md-2 col-md-offset-1 control-label">关键词:</label>
        <div class="col-md-7">
            <input id="keywords" class="form-control" type="text" name="keywords" placeholder="多个关键词以空格隔开"
                   value="<?php echo $this->form['keywords']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 col-md-offset-1 control-label">简介:</label>
        <div class="col-md-7">
            <textarea class="form-control" id="intro" name="intro" rows="3" cols="50"
                      maxlength="500"><?php echo $this->form['intro']; ?></textarea>
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>

    <div class="form-group ">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">联系人:</label>
        <div class="col-md-7">
            <input id="linkman" class="form-control" type="text" name="linkman"
                   value="<?php echo $this->form['linkman']; ?>">
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>

    <div class="form-group ">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">联系人手机号码:</label>
        <div class="col-md-7">
            <input id="tel" class="form-control" type="text" name="tel" value="<?php echo $this->form['tel']; ?>">
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>

    <div class="form-group hidden">
        <label class="col-md-2 col-md-offset-1 control-label">备注:</label>
        <div class="col-md-7">
            <!--<input id="info" class="form-control" type="text" name="info"  value="<?php echo $this->form['info']; ?>">-->
            <textarea class="form-control" id="info" name="info" rows="3" cols="50"><?php echo $info; ?></textarea>
        </div>
    </div>

    <div class="form-group ">
        <label class="col-md-2 col-md-offset-1 control-label Dl-required">deepleaper负责人:</label>
        <div class="col-md-7">
            <input id="duty_user" class="form-control" type="text" name="duty_user"
                   value="<?php echo $this->form['duty_user']; ?>">
        </div>
        <span class="help-block col-md-7 col-md-offset-3"></span>
    </div>
    <div class="row submit_box">
        <div class="submit_btn_wrapper">
            <div class="submit_btn" id="cancel">
                返回列表
            </div>
            <div class="submit_btn submit_btn_default submit_btn_active" id="submit">
                完成修改
            </div>
        </div>
    </div>

</form>


<script type="text/javascript">

    checkActionAuth('/media/media', 2);

    //媒体账户的API
    getmediumAPI(getmediumAPIonSuccess);
    function getmediumAPIonSuccess(result) {
        var req = JSON.parse(result);
        if (req.status == 1) {
            var data = req.data;
            var option = '';
            for (var i = 0; i < data.length; i++) {
                option += '<option value="' + data[i].id + '">';  //<optgroup> 标签定义选项组。
                option += data[i].name;
                option += '</option>';
            }
            $('#medium').html(option);
        } else {
            layer.msg(req.msg);
        }
    }

    //获取URL参数来判断登录类型，选择下发数据
    var Request = new Object();
    Request = GetRequest();
    function GetRequest() {
        var url = location.search; //获取url中"?"符后的字串
        var theRequest = new Object();
        if (url.indexOf("?") != -1) {
            var str = url.substr(1);
            strs = str.split("&");
            for (var i = 0; i < strs.length; i++) {
                theRequest[strs[i].split("=")[0]] = unescape(strs[i].split("=")[1]);
            }
        }
        return theRequest;
    }

    var uid;
    uid = Request.uid;
    getmediumbyuidAPI(uid, getmediumbyuidAPIonSuccess);
    function getmediumbyuidAPIonSuccess(result) {
        var req = JSON.parse(result);
        if (req.status == 1) {
            $("#medium option[value='" + req.data.selected.id + "']").prop('selected', 'selected').change();

        } else {
            layer.msg(req.msg);
        }
    }

    $(function () {
        function objInit(obj) {
            return $(obj).html("<option>请选择</option>");
        }

        var arrData =<?php echo $this->mediaclass_menu2;?>;
        var subcategory_select = "<?php echo $this->form['class'];?>";

        $("#selF").change(function () {
            $('#selT').parents(".selTWrapper").html('<select id="selT" name="class" class="form-control selectpicker"><option>二级分类</option></select>');
            objInit("#selT");
            objInit("#selC");
            $.each(arrData, function (pF, pS) {
                if ($("#selF option:selected").text() == pF) {
                    //遍历数据增加品牌项
                    $.each(pS, function (pT, pC) {
                        $("#selT").append('<option value = ' + pC + '>' + pT + '</option>');
                    });

                    //品牌列表change事件
                    $("#selT").change(function () {
                        objInit("#selC");
                        $.each(pS, function (pT, pC) {
                            if ($("#selT option:selected").text() == pT) {
                                $.each(pC.split(","), function () {
                                    $("#selC").append('<option>' + this + '</option>');
                                });
                            }
                        });
                    });
                }
                $(".selectpicker").selectpicker('refresh');
            });
        });

        $.each(arrData, function (pF, pS) {
            var isFind = false;
            $.each(pS, function (pT, pC) {

                if (pC == subcategory_select) {
                    $("#selT").append("<option value = " + pC + " selected='selected'>" + pT + "</option>");
                    $("#selF").append("<option selected='selected'>" + pF + "</option>");
                    isFind = true;
                } else {
                    $("#selT").append("<option value = " + pC + ">" + pT + "</option>");
                }

            });
            if (!isFind) {
                $("#selF").append("<option>" + pF + "</option>");
            }
        });

        $('#selF').change();
        $('#selT option[value=' + subcategory_select + ']').prop('selected', 'selected');
        $('#selT').selectpicker('refresh');

    });
</script>
<script>
    $('#name').blur(function () {
        if (!vaWordNumberLimit1_25($(this).val())) {
            vaError($('#name'), '名称长度应为1-50个字符:汉字占2个字符');
        } else {
            vaSuccess($('#name'));
        }
    });
    $('#linkman').blur(function () {
        if (!vaIsNotNull($(this).val())) {
            vaError($('#linkman'), '联系人不能为空');
        } else {
            vaSuccess($('#linkman'));
        }
    });
    $('#tel').blur(function () {
        if (!vaIsNotNull($('#tel').val())) {
            vaError($('#tel'), '请输入联系人手机号码');
        } else if (!validatePhoneNum($('#tel').val())) {
            vaError($('#tel'), '手机号码格式错误');
        } else {
            vaSuccess($('#tel'));
        }
    });
    $('#url').blur(function () {
        if (!vaIsUrl($(this).val())) {
            vaError($(this), '网站地址输入有误');
        } else {
            vaSuccess($(this));
        }
    });
    $('#bundle_id').blur(function () {
        if (!vaIsNotNull($(this).val())) {
            vaError($(this), '程序主包名不能为空');
        } else {
            vaSuccess($(this));
        }
    });
    if ($('#type_web').prop('checked')) {
        $("#url_group").show();
    }
    if ($('#type_app').prop('checked')) {
        $("#bundle_id_group").show();
    }

    //校验规则：渠道不能空；手机号码可以空、校验格式；
    function mediaeditVilidate() {
        $("#Deepleaper_loading").show();
        var name = $('#name');
        var nameVal = name.val();
        var linkman = $('#linkman');
        var linkmanVal = linkman.val();
        var tel = $('#tel');
        var telVal = tel.val();
        var url = $('#url');
        var urlVal = url.val();
        var duty_user = $('#duty_user');
        var duty_userVal = duty_user.val();
        if (!vaWordNumberLimit1_25(nameVal)) {
            $("#Deepleaper_loading").hide();
            vaError(name, '名称长度应为1-50个字符:汉字占2个字符');
            return false;
        } else if (!vaIsUrlorNull(urlVal)) {
            $("#Deepleaper_loading").hide();
            vaError(url, '网站地址输入有误');
            return false;
        } else if (!vaIsNotNull(linkmanVal)) {
            $("#Deepleaper_loading").hide();
            vaError(linkman, '联系人不能为空');
            return false;
        } else if (!vaIsNotNull(telVal)) {
            $("#Deepleaper_loading").hide();
            vaError(tel, '请输入联系人手机号码');
            return false;
        } else if (!validatePhoneNum(telVal)) {
            $("#Deepleaper_loading").hide();
            vaError(tel, '手机号码格式错误');
            return false;
        } else if (!vaIsNotNull(duty_userVal)) {
            $("#Deepleaper_loading").hide();
            vaError(duty_user, 'deepleaper负责人不能为空');
            return false;
        } else if ($('#type_web').prop('checked') && !vaIsUrl($('#url').val())) {
            $("#Deepleaper_loading").hide();
            vaError($('#url'), '网站地址输入有误');
            return false;
        } else if ($('#type_app').prop('checked') && !vaIsNotNull($('#bundle_id').val())) {
            $("#Deepleaper_loading").hide();
            vaError($('#bundle_id'), '程序主包名不能为空');
            return false;
        } else {
            $("#Deepleaper_loading").hide();
            return checkFormValidByBackend();
        }
    }

    function checkFormValidByBackend() {
        // ---- 拼装好的的提交form
        var data = {
            'name': $('#name').val(),
            'medium': $('select[id="medium"]').val(),
            'class': $('#selT').val(),
            'url': $('#url').val(),
            'keywords': $('#keywords').val(),
            'intro': $('#intro').val(),
            'linkman': $('#linkman').val(),
            'tel': $('#tel').val(),
            'info': $('#info').val(),
            'duty_user': $('#duty_user').val(),
            'uid': '<?php echo $_GET["uid"]; ?>',
            'bundle_id': $('#bundle_id').val(),
            'type':$("input[name=type]:checked").val()
        };
        var valid;

        checkAddMediaFormValidAPI(data,function (result) {
            var req = JSON.parse(result);
            if (req.status == 1) {
                if (req.data.res) {
                    // 验证成功
                    valid = true;
                } else {
                    // 验证失败
                    valid = false;
                    for (var key in req.data.error) {
                        vaError($('[name=' + key + ']'), req.data.error[key]);
                    }
                }
            } else {
                layer.msg(req.msg);
            }
        });

        return valid;
    }
    // 路径导航栏 结束
    $("#submit").bind('click', function () {
        if (!mediaeditVilidate()) {
            return false;
        }
        var obj = {
            'name': $('#name').val(),
            'medium': $('select[id="medium"]').val(),//这个地方传ID
            'class': $('#selT').val(),
            'bundle_id': $("input[name=type]:checked").val() == 2 ? $('#url').val() : $('#bundle_id').val(),
            'keywords': $('#keywords').val(),
            'intro': $('#intro').val(),
            'linkman': $('#linkman').val(),
            'tel': $('#tel').val(),
            'info': $('#info').val(),
            'duty_user': $('#duty_user').val(),
            'uid': '<?php echo $_GET["uid"]; ?>',
            'type': $("input[name=type]:checked").val()
        };
        mediaeditAPI(obj, function (result) {
            var req = JSON.parse(result);
            if (req.status == 1) {
                layer.msg('媒体修改成功');
                setTimeout(function () {
                    window.location = '/media/media';
                }, 1000)
            } else {
                layer.msg(req.msg);
            }
        })
    });
    $("#cancel").bind('click', function () {
        window.location = '/media/media';
    });

</script>
