<?php
echo $this->partial('layout/listPublicHeader2.phtml');
echo $this->partial('layout/tablePublic.phtml');
?>
<script>

    var ListPageConfig = {
        tableId: '#table',   // 表格id
        func: function (data) {
        },
        tableIndexCol: 'uid', //数据索引字段 一般为 uid 或者 id
        table: {           //表格配置
            url: '/media/media',
            queryParams: 'queryParams',
            toolbar: '#toolbar',
            showColumns: true,
            searchAlign: 'left',
            pagination: true,
            pageSize: 50,
            pageList: [30, 50, 100],
            showRefresh: true,
            sortName: 'create_time',
            sortOrder: 'desc',
            sidePagination: 'server',
            striped: true,
            cookie: true,
            cookieIdTable: 'replacebyListJS',
            cookiesEnabled: ['bs.table.pageNumber'],
            cookiePath: '/',
            columns: [{
                checkbox: true
            }, {
                field: 'name',
                title: '媒体名称',
                formatter: function (value, row, index) {
                    return '<span class="cutValue">' + cutstrbyChar(value, 16) + '</span>'
                },
                events: {
                    'mouseenter .cutValue': function (e, value, row, index) {
                        if (getCharLength(value) > 16) {
                            layer.tips(value, e.target, {
                                tips: [1, '#353538'],
                                area: ['auto', 'auto']
                            });
                        }
                    },
                    'mouseleave .cutValue': function (e, value, row, index) {
                        if (getCharLength(value) > 16) {
                            layer.closeAll()
                        }
                    }
                }
            }, {
                field: 'type',
                title: '媒体类型'
            }, {
                field: 'class_name',
                title: '媒体分类',

            }, {
                field: 'medium_name',//'company_name',
                title: '媒体账户',
                formatter: function (value, row, index) {
//                    console.log('value',value);
//                    return value;
                    if(!value)
                    {
                        return value;
                    }else {
                        return '<span class="cutValue">' + cutstrbyChar(value, 10) + '</span>'
                    }
                },
                events: {
                    'mouseenter .cutValue': function (e, value, row, index) {
                        if (getCharLength(value) > 10) {
                            layer.tips(value, e.target, {
                                tips: [1, '#353538'],
                                area: ['auto', 'auto']
                            });
                        }
                    },
                    'mouseleave .cutValue': function (e, value, row, index) {
                        if (getCharLength(value) > 10) {
                            layer.closeAll()
                        }
                    }
                }
            }, {
                field: 'duty_user',
                title: 'deepleaper负责人',
                formatter: function (value, row, index) {
                    return '<span class="cutValue">' + cutstrbyChar(value, 10) + '</span>'
                },
                events: {
                    'mouseenter .cutValue': function (e, value, row, index) {
                        if (getCharLength(value) > 10) {
                            layer.tips(value, e.target, {
                                tips: [1, '#353538'],
                                area: ['auto', 'auto']
                            });
                        }
                    },
                    'mouseleave .cutValue': function (e, value, row, index) {
                        if (getCharLength(value) > 10) {
                            layer.closeAll()
                        }
                    }
                }

            }, {

                field: 'create_time',
                title: '创建时间',

            }, {

                field: 'createUserName',
                title: '创建/修改人',

            }, {
                field: 'do',
                title: '操作',
                align: 'center',
                formatter: 'List.operateFormatter',
                events: 'List.operateEvents',
                width: '100px'
            }]
        },
        url: {
            add: '/media/mediaadd',         //添加 数据 html 地址
            edit: '/media/mediaedit',         //编辑数据 html 地址
            info: '/media/mediainfo',         //编辑数据 html 地址
            del: '/media/mediadel',         //删除数据地址
            detail: false                      //详细内容地址,为空则取编辑的地址
        },
        action: {
            //detail: true,
            info: true,
            edit: true,
            del: true,
        },
        title: {
            addTitle: '添加媒体',
            editTitle: '编辑媒体',
            infoTitle: '查看媒体ID',
        },
        showDetail: false         //是否显示详细信息按钮
    }


    var auth = getAuthorityByUrl('/media/media');
    function checkAuthority() {
        if (auth == 0) {
            // 用户无耻的绕过了验证，你就说怎么办吧
            ListPageConfig.action = {
                info: false,
                edit: false,
                del: false
            };
            toFirstLegalPage();
        } else if (auth == 1) {
            ListPageConfig.action = {
                info: true,
                edit: false,
                del: false
            };
        } else if (auth == 2) {
            ListPageConfig.action = {
                info: true,
                edit: true,
                //   del: true
                del: false
            };
        }
    }
    checkAuthority();

</script>

<div id="toolbar">
    <div class="btn-group pull-left" id="for_change">
        <div class="btn deepleaper-btn-normal plus">
            <img src="/img/icon/icon_plussign.png" class="btn-icon">添加媒体
        </div>
    </div>
    <div class="input-group pull-left deepleaper-search-control" style='width:250px;'>
        <input type="text" id="searchKeyword" class="form-control" placeholder="媒体名称" value="" name="search">
        <span class="input-group-btn">
			<a id="ok" class="btn btn-default dropdown-toggle deepleaper-search-btn" type="button"
               data-toggle="dropdown">
                <span class="glyphicon glyphicon-search"></span>
            </a>
		</span>
    </div>
</div>
<table id="table" class="list-table"></table>
<?php
echo $this->partial('layout/listPublicFooter3.phtml');
?>

<script>
    hideChangeBtnIfNeed(auth);
</script>