<?php
echo $this->renderFile('@app/views/layouts/listPublicHeader2.phtml');
?>
    <link rel="stylesheet" href="/css/bootstrap-editable.css"/>
    <script type="text/javascript" src="/js/bootstrap-editable.js"></script>

    <div id="toolbar">
        <div class="form-inline" role="form" style="padding-bottom: 10px">
            <div class="form-group">
                <span>开始日期: </span>
                <input id="begin_date" name="begin_date" class="form-control w70" type="string" value="">
            </div>

            <div class="form-group">
                <span>结束日期: </span>
                <input id="end_date" name="end_date" class="form-control w70" type="string" value="">
            </div>
            <br/>

            <div class="form-group">
                <span>广告主: </span>
                <select name="client" id="client" class="selectpicker show-tick">
                    <option value="全部">全部</option>

                </select>
            </div>

            <div class="form-group">
                <span>订单: </span>
                <select name="order" id="order" class="selectpicker show-tick">
                    <option value="全部">全部</option>
                </select>
            </div>

            <div class="form-group">
                <span>广告: </span>
                <select name="ad" id="ad" class="selectpicker show-tick">
                    <option value="全部">全部</option>

                </select>
            </div>

            <div class="form-group">
                <span>素材: </span>
                <select name="material" id="material" class="selectpicker show-tick">
                    <option value="全部">全部</option>

                </select>
            </div>

            <button id="ok" type="submit" class="btn btn-default">OK</button>
            <div class="form-group">
                <input type="button" class="form-control" value="下载报表" id="downloadTable">
            </div>
        </div>
        <div id="echarsBox" style="width: 100%;height:400px;"></div>
        <form role="form" style="padding: 19px 0 ">
            选择报表对比项：
            <div id="comparision">
            </div>
        </form>
    </div>

    <script type="text/javascript">
        function GetDateStr(AddDayCount) {
            var dd = new Date();
            dd.setDate(dd.getDate() + AddDayCount);//获取AddDayCount天后的日期
            var y = dd.getFullYear();
            var m = dd.getMonth() + 1;//获取当前月份的日期
            var d = dd.getDate();
            return y + "/" + m + "/" + d;
        }

        (function () {
            bindRangeDatepicker($('#begin_date'), $('#end_date'), addDate(new Date, -7), addDate(new Date(), -1));
        })();
    </script>
    <script>

        checkActionAuth('/report/day', 1);
        //      保存级联数组
        var getListData = [];
        reportGetList(reportGetListSuccess);
        function reportGetListSuccess(result) {
            var client = $("#client");
            var order = $("#order");
            var ad = $("#ad");
            var material = $("#material");
//          全部1，2，3，4级存储
//            var clientAllArr = [];
//            var orderAllArr = [];
//            var adAllArr = [];
//            var materialAllArr = [];
            var res = JSON.parse(result);

            if (res.status == '1') {
                getListData = res.data;
//              初始化一级菜单
                var clientDom = '<option value="全部">全部</option>';
//                var orderDom = '<option value="全部">全部</option>';
//                var adDom = '<option value="全部">全部</option>';
//                var materialDom = '<option value="全部">全部</option>';
                for (var i = 0; i < getListData.length; i++) {
                    clientDom += '<option value="' + getListData[i].c_uid + '">' + getListData[i].c_name + '</option>';
                }
//                for (var i = 0; i < getListData.length; i++) {
//                    clientDom += '<option value="' + getListData[i].c_uid + '">' + getListData[i].c_name + '</option>';
//                    clientAllArr.push(getListData[i]);
//                    for (var j = 0; j < getListData[i].child.length; j++) {
//                        orderDom += '<option value="' + getListData[i].child[j].o_uid + '">' + getListData[i].child[j].o_name + '</option>';
//                        orderAllArr.push(getListData[i].child[j]);
//                        for (var m = 0; m < getListData[i].child[j].child.length; m++) {
//                            adDom += '<option value="' + getListData[i].child[j].child[m].ad_uid + '">' + getListData[i].child[j].child[m].ad_name + '</option>';
//                            adAllArr.push(getListData[i].child[j].child[m]);
//                            for (var n = 0; n < getListData[i].child[j].child[m].child.length; n++) {
//                                materialDom += '<option value="' + getListData[i].child[j].child[m].child[n].m_uid + '">' + getListData[i].child[j].child[m].child[n].m_name + '</option>';
//                                materialAllArr.push(getListData[i].child[j].child[m].child[n]);
//                            }
//                        }
//                    }
//                }
//                0.0不需要了屏蔽掉
//                client.html(clientDom);
//                order.html(orderDom);
//                ad.html(adDom);
//                material.html(materialDom);

                client.html(clientDom);
                var orderListData = [];
//              选中一级菜单
                client.change(function () {
                    order.html('<option value="全部">全部</option>');
                    ad.html('<option value="全部">全部</option>');
                    material.html('<option value="全部">全部</option>');
                    var orderDom = '<option value="全部">全部</option>';
                    $.each(getListData, function (i, clientItem) {
//                      存个二级菜单的dataList
                        $.each(clientItem.child, function (j, orderItem) {
                            orderListData.push(orderItem);
                        });
                        if ($("#client option:selected").val() == clientItem.c_uid) {
                            $.each(clientItem.child, function (j, orderItem) {
                                orderDom += '<option value = ' + orderItem.o_uid + '>' + orderItem.o_name + '</option>';
                            });
                            order.html(orderDom);
                        }
                    });

                    $(".selectpicker").selectpicker('refresh');
                });

                var adListData = [];
//              选中二级菜单
                order.change(function () {
                    ad.html('<option value="全部">全部</option>');
                    material.html('<option value="全部">全部</option>');
                    var adDom = '<option value="全部">全部</option>';
                    $.each(orderListData, function (i, orderItem) {
//                      存个三级菜单的dataList
                        $.each(orderItem.child, function (j, adItem) {
                            adListData.push(adItem);
                        });
                        if ($("#order option:selected").val() == orderItem.o_uid) {
                            $.each(orderItem.child, function (j, adItem) {
                                adDom += '<option value = ' + adItem.ad_uid + '>' + adItem.ad_name + '</option>';
                            });
                            ad.html(adDom);
                        }
                    });
                    $(".selectpicker").selectpicker('refresh');
                });

//              选中三级菜单
                ad.change(function () {
                    material.html('<option value="全部">全部</option>');
                    var materialDom = '<option value="全部">全部</option>';
                    $.each(adListData, function (i, adItem) {
                        if ($("#ad option:selected").val() == adItem.ad_uid) {
                            $.each(adItem.child, function (j, mItem) {
                                materialDom += '<option value = ' + mItem.m_uid + '>' + mItem.m_name + '</option>';
                            });
                            console.log(materialDom);
                            material.html(materialDom);
                        }
                    });
                    $(".selectpicker").selectpicker('refresh');
                });

            } else {
                console.log('投放报表级联菜单获取失败');
            }
        }
    </script>
    <script type="text/javascript" src="/js/echartsCtl.js"></script>
    <!--    初始化echarts对比字段控制器-->
    <script type="text/javascript">
        var comparision = [
            {
                field: "imp",
                name: "曝光量",
                checked: true
            },
            {
                field: "u_imp",
                name: "唯一曝光量",
                checked: true
            },
            {
                field: "click",
                name: "点击量",
                checked: false
            },
            {
                field: "ctr",
                name: "点击率",
                checked: false
            },
            {
                field: "cpm",
                name: "eCPM",
                checked: false
            },
            {
                field: "cpc",
                name: "eCPC",
                checked: false
            },
            {
                field: "expense",
                name: "花费",
                checked: false
            }
        ];
        comparisionInit($('#comparision'), comparision);
        function draw(xx) {
            var date_arr = [];
            var obj = {};
            //echartsCtlSelected存储当前选中需要图表显示的字段
            var echartsCtlSelected = [];
            $("input[name='echartsCtl']:checked").each(function (index, element) {
                var name = $(element).val();
                var fieldCol = $(element).attr('field');
                var fieldObj = [];
                var fieldObjOriginal = [];//用于图标标记显示
                for (x in xx.data) {
                    date_arr[x] = xx.data[x].date;
                    for (h in xx.data[x]) {
                        if (h == fieldCol) {
                            if (xx.data[x][h] == "-") {
                                fieldObj[x] = 0;
                            } else {
                                fieldObj[x] = xx.data[x][h];
                            }
                            fieldObjOriginal[x] = xx.data[x][h];
                        } else {

                        }
                    }
                }
                obj[name] = fieldObjOriginal;
//              处理原始数据为百分比形式formatterObj
                var maxVal = Math.max.apply(null, fieldObj);
                var formatterObj = [];//
                for (var i = 0; i < fieldObj.length; i++) {
                    if(maxVal == 0){
                        formatterObj[i] = 0;
                    }else{
                        formatterObj[i] = parseFloat(fieldObj[i] / maxVal * 100);
                    }
                }
                echartsCtlSelected[index] = {
                    name: name,
                    type: 'line',
                    symbol: 'circle',
                    symbolSize: 8,
                    connectNulls: true,
                    data: formatterObj
                };
            });

            var myChart = echarts.init(document.getElementById('echarsBox'));
            option = {
                title: {
                    show: false,
                    text: '日流量报表'
                },
                tooltip: {
                    trigger: 'axis',
                    hideDelay: 1000,
                    formatter: function (params) {//渲染原始数据
                        var tooltipHtml = '';
                        for (var i = 0; i < params.length; i++) {
                            if (params[i].data != undefined) {
                                tooltipHtml += '<span style="margin-left:20px;display:inline-block;width:80px;color: ' + params[i].color + ';">' + params[i].seriesName + '</span><span style="display:inline-block;width: 100px;color: ' + params[i].color + ';">' + obj[params[i].seriesName][params[i].dataIndex] + '</span>';
                                tooltipHtml += '<br/>';
                            }
                        }

                        return tooltipHtml;
                    },
                    backgroundColor: 'rgba(255,255,255,0.9)',
                    borderColor: '#e4e4e4',
                    borderWidth: 1,
                    padding: [10, 20, 10, 10],
                    axisPointer: {
                        type: 'line',
                        lineStyle: {
                            color: '#cad2e2',
                            type: 'dotted'
                        }
                    }
                },
                grid: {
                    left: '3%',
                    right: '4%',
                    bottom: '3%',
                    containLabel: true
                },
                toolbox: {
                    feature: {
                        saveAsImage: {}
                    }
                },
                xAxis: {
                    type: 'category',
                    boundaryGap: false,
                    axisLine: {
                        lineStyle: {
                            color: '#eeeeee'
                        }
                    },
                    axisTick: {
                        show: false
                    },
                    axisLabel: {
                        margin: 15,
                        textStyle: {
                            color: '#c6c6cc'
                        }
                    },
                    data: date_arr
                },
                yAxis: {
                    type: 'value',
                    scale: true,
                    min: '0',
                    max: '120',
                    axisLine: {
                        show: false
                    },
                    axisTick: {
                        show: false
                    },
                    axisLabel: {
                        show: false
                    },
                    splitLine: {
                        show: false
                    }
                },
                color: ['#abaa92', '#56b7ad', '#a38f24', '#da8888', '#aaaef8', '#64afdf', '#51af66', '#7177e4', '#c23531', '#2f4554', '#61a0a8', '#d48265', '#91c7ae', '#749f83', '#ca8622', '#bda29a', '#6e7074', '#546570', '#c4ccd3'],
                backgroundColor: "#f9f9f9",
                series: echartsCtlSelected
            };
            myChart.setOption(option);
        }
        var ListPageConfig = {
            func: function (data) {//绘制echarts
                draw(data);
            },
            tableId: '#table',   // 表格id
            tableIndexCol: 'uid', //数据索引字段 一般为 uid 或者 id
            table: {           //表格配置
                url: '/report/day',
                queryParams: 'queryParams',
                toolbar: '#toolbar',
                showColumns: true,
                searchAlign: 'left',
                pagination: false,
                pageSize: 25,  //获取所有数据,建立二级结构
                sortOrder: 'desc',

                sidePagination: 'server',
                cookie: true,
                cookieIdTable: 'replacebyListJS',cookiesEnabled:['bs.table.pageNumber'],
                cookiePath: '/',
                toolbarAlign: 'dpmiddle',

                columns: [{
                    checkbox: true
                }, {
                    field: 'date',
                    title: '日期'
                }, {
                    field: 'imp',
                    title: '曝光量',
                    sortable: true
                }, {
                    field: 'u_imp',
                    title: '唯一曝光量',
                    sortable: true
                }, {
                    field: 'click',
                    title: '点击量',
                    sortable: true
                }, {
                    field: 'ctr',
                    title: '点击率(%)',
                    sortable: true
                }, {

                    field: 'cpm',
                    title: 'CPM',
                    sortable: true

                }, {
                    field: 'cpc',
                    title: 'CPC',
                    sortable: true
                }, {
                    field: 'expense',
                    title: '花费',
                    sortable: true
                }]
            },

            title: {
                addTitle: '添加订单',
                editTitle: '编辑订单'
            },
            showDetail: false         //是否显示详细信息按钮
        };
        //下载报表
        $("#downloadTable").on('click', function () {
            var url = '/report/exportcsv?type=day&begin_date=' + encodeURI($("#begin_date").val()) + '&end_date=' + encodeURI($("#end_date").val()) + '&client=' + encodeURI($("#client").val()) + '&order=' + encodeURI($("#order").val()) + '&ad=' + encodeURI($("#ad").val());
            window.open(url);
        })


    </script>
    <table id="table" class="list-table"></table>

<?php
echo $this->renderFile('@app/views/layouts/listPublicFooter2.phtml');
?>