// export const DEPOSITORY_CHANGE_LOADINGSTATUS = 'DEPOSITORY_CHANGE_LOADINGSTATUS';
// export const DEPOSITORY_CHANGE_PAGEID = 'DEPOSITORY_CHANGE_PAGEID';
// export const DEPOSITORY_CHANGE_LANDPAGEURL = 'DEPOSITORY_CHANGE_LANDPAGEURL';
// export const DEPOSITORY_CHANGE_STATISTICSVISIBLE = 'DEPOSITORY_CHANGE_STATISTICSVISIBLE';
// export const DEPOSITORY_CHANGE_LISTTEMPLATESBYCATEGORY = 'DEPOSITORY_CHANGE_LISTTEMPLATESBYCATEGORY';
// export const DEPOSITORY_CHANGE_CHECKEDTEMPLATE = 'DEPOSITORY_CHANGE_CHECKEDTEMPLATE';
// export const DEPOSITORY_CHANGE_CHECKEDCATEGORY = 'DEPOSITORY_CHANGE_CHECKEDCATEGORY';
// export const DEPOSITORY_CHANGE_TITLE = 'DEPOSITORY_CHANGE_TITLE';
// export const DEPOSITORY_CHANGE_ORDER = 'DEPOSITORY_CHANGE_ORDER';
// export const DEPOSITORY_CHANGE_STATISTICSID = 'DEPOSITORY_CHANGE_STATISTICSID';
// export const DEPOSITORY_CHANGE_LEAVECONFIRMVISIBLE = 'DEPOSITORY_CHANGE_LEAVECONFIRMVISIBLE';
// export const DEPOSITORY_CHANGE_PID = 'DEPOSITORY_CHANGE_PID';
// export const DEPOSITORY_CHANGE_PIDS = 'DEPOSITORY_CHANGE_PIDS';
// export const DEPOSITORY_CHANGE_GOODSLIBRARY = 'DEPOSITORY_CHANGE_GOODSLIBRARY';
// export const DEPOSITORY_CHANGE_SEARCHCONDITION = 'DEPOSITORY_CHANGE_SEARCHCONDITION';
// export const DEPOSITORY_CHANGE_SEARCHCONDITIONNAME = 'DEPOSITORY_CHANGE_SEARCHCONDITIONNAME';
// export const DEPOSITORY_CHANGE_SEARCHTEXT = 'DEPOSITORY_CHANGE_SEARCHTEXT';
// export const DEPOSITORY_CHANGE_SELECTIONRESULT = 'DEPOSITORY_CHANGE_SELECTIONRESULT';
// export const DEPOSITORY_CHANGE_TOTAL = 'DEPOSITORY_CHANGE_TOTAL';
// export const DEPOSITORY_CHANGE_SECTIONLIST = 'DEPOSITORY_CHANGE_SECTIONLIST';
// export const DEPOSITORY_INIT = 'DEPOSITORY_INIT';


export const USERINFO_SET_USERNAME = 'USERINFO_SET_USERNAME';
export const USERINFO_SET_UID = 'USERINFO_SET_UID';
export const USERINFO_INIT = 'USERINFO_INIT';
export const USERINFO_SET_ROLE = 'USERINFO_SET_ROLE';

