<?php if($this->item){
    $name   = $this->item['name'];
    $uid    = $this->item['uid'];
    $info    = $this->item['info'];

?>

<form id="edit" method="post" action="/materiel/materielsave" class="form-horizontal list-form" novalidate="novalidate">

    <div class="form-group ">
        <label class="col-sm-3 control-label">素材名称</label>
        <div class="col-sm-6 ">
            <input id="name" type="text" name="name" class="form-control" check-type="required" required-message="不能为空。"  value="<?php echo $name;?>">
            <input id="uid" class="form-control" type="hidden" name="uid"  value="<?php echo $uid;?>">
        </div>
    </div>
     
    <!--
    <div class="form-group ">
        <label class="col-sm-3 control-label">素材组</label>
        <div class="col-sm-6 ">
            <select name="group" class="form-control selectpicker dropup" data-live-search="true">
				<?php foreach($this->group_menu as $key => $val):?>
				<option value="<?php echo $key?>" <?php if($this->item['group'] ==$key) echo 'selected="selected"'?>><?php echo $val;?></option>
				<?php endforeach;?>
            </select>
        </div>
    </div>
    -->
    
     <div class="form-group ">
        <label class="col-sm-3 control-label">素材类型</label>
        <div class="col-sm-6 ">
            <select name="type" class="form-control selectpicker dropup" data-live-search="true">
				<?php foreach($this->type_menu as $key => $val):?>
				<option value="<?php echo $key?>" <?php if($this->item['type'] ==$key) echo 'selected="selected"'?>><?php echo $val;?></option>
				<?php endforeach;?>
            </select>
        </div>
    </div>
    
    <div class="form-group ">
        <label class="col-sm-3 control-label">选择上传文件</label>
        <div class="col-sm-6 ">
            <input id="info" class="form-control" type="text" name="info"  value="<?php echo $info;?>">
            
            <img src="" />小于1MB，限swf/jpg/png/gif/flv格式
        </div>
    </div>

    <div class="form-group ">
        <label class="col-sm-3 control-label">默认宽度</label>
        <div class="col-sm-6 ">
            <input id="info" class="form-control" type="text" name="info"  value="<?php echo $this->item['w'];?>">PX
        </div>
    </div>
    
    <div class="form-group ">
        <label class="col-sm-3 control-label">默认高度</label>
        <div class="col-sm-6 ">
            <input id="info" class="form-control" type="text" name="info"  value="<?php echo $this->item['h'];?>">PX
        </div>
    </div>
    
</form>
<?php }?>

<script type="text/javascript">

    checkActionAuth('/materiel/materiel', 2);
</script>