<form method="post" class="form-horizontal list-form" onsubmit="return false;">

    <div class="form-group ">
        <label class="col-sm-3 control-label">邮箱</label>
        <div class="col-sm-6 ">
            <input id="mail" type="text" name="mail" class="form-control" value="<?php echo $user[mail]?>" check-type="required" required-message="不能为空。" readonly>
        </div>
    </div>
    <div class="form-group ">
        <label class="col-sm-3 control-label">姓名</label>
        <div class="col-sm-6 ">
            <input id="name" type="text" name="name" class="form-control" value="<?php echo $user[name]?>" check-type="required" required-message="不能为空。" readonly>
        </div>
    </div>
    
    <?php if($clientList):?>
    <div class="form-group ">
        <label class="col-sm-3 control-label">已关联广告主</label>
        <div class="col-sm-6  ">
            <select name="pid" class="form-control selectpicker" data-live-search="true" check-type="required" required-message="不能为空。">
                <option value="">点击查看</option>
                <?php foreach($clientList as $key => $val):?>
                <option value="<?php echo $key?>"><?php echo $val?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>
    <?php endif;?>
    
    <div class="form-group ">
        <label class="col-sm-3 control-label">用户类型</label>
        <div class="col-sm-6  ">
            <select name="power" class="form-control selectpicker" disabled data-live-search="true" check-type="required" required-message="不能为空。">
                <?php foreach($powerSelect as $val):?>
                    <option value="<?php echo $val['value'];?>" <?php echo $val['selected']?> ><?php echo $val['name'];?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>

    <div class="form-group ">
        <label class="col-sm-3 control-label">权限</label>
        <div class="col-sm-6 ">
            <select id="permission" class="form-control selectpicker" disabled data-live-search="true"  name="permission">
                <?php foreach($permissionSelect as $val):?>
                <option value="<?php echo $val[value]?>" <?php echo $val[selected]?>><?php echo $val[name]?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>

    <div class="form-group ">
        <label class="col-sm-3 control-label">财务数据</label>
        <div class="col-sm-6 ">
            <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default active">
                    <input checked type="radio" name="finance" value="1">开启
                </label>
                <label class="btn btn-default ">
                    <input type="radio" name="finance" value="0">关闭
                </label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-3 control-label">上次登录时间</label>
        <div class="col-sm-6 ">
            <input type="text" class="form-control" readonly="" value="<?php echo date('Y-m-d H:i:s', $user['last_time'])?>">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">上次登录IP</label>
        <div class="col-sm-6 ">
            <input type="text" class="form-control" readonly="" value="<?php echo $user['last_ip']?>">
        </div>
    </div>

</form>


