<!--媒体系统 广告位报表-->
<?php
echo $this->renderFile('@app/views/layouts/listPublicHeader2.phtml');
echo $this->renderFile('@app/views/layouts/tablePublic.phtml');
?>
<div class="toolbar">
    <div class="container-fluid" style="margin: 20px 0;">
        <div class="row">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <div class="input-group date dl-date-range-wrapper">
                        <input type="text" class="form-control dl-date-range-input" id="searchDate">
                        <span class="caret dl-date-range-input-icon"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 10px">
            <div class="form-inline" role="form">
                <div class="btn-group dl-custom-filter" role="group">
                    <button type="button" class="btn dl-btn-primary dl-custom-filter-all active">全部</button>
                    <div class="btn-group dl-custom-filter-custom" role="group">
                        <select id="slot_class" class="selectpicker" data-width="100%" multiple data-size="10"
                                title="筛选广告位类型">
                        </select>
                    </div>
                </div>
                <div class="btn-group dl-custom-filter" role="group" style="margin-left: 30px">
                    <button type="button" class="btn dl-btn-primary dl-custom-filter-all active">全部</button>
                    <div class="btn-group dl-custom-filter-custom" role="group">
                        <select id="slot" class="selectpicker" data-width="100%" multiple data-size="10"
                                title="筛选广告位">
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="echarsBox" style="width: 100%;height:400px;">
    <div id="line-container" style="width: 100%;height:400px">
        <div id="main"></div>
    </div>
</div>

<div id="toolbar">
    <div class="form-inline" role="form">
        <div class="btn-group dl-table-filter" id="dimensionSplitWrapper" style="width: 87px;">
            <select id="dimensionSplit" class="selectpicker" data-width="100%" title="维度拆分">
                <option value="1">日期</option>
                <option value="2" selected>广告位</option>
            </select>
        </div>
        <div class="form-group download-table">
            <input type="button" class="form-control btn btn-default" value="下载报表" id="downloadTable">
        </div>
    </div>
</div>
<table id="table" class="list-table"></table>

<?php
echo $this->renderFile('@app/views/layouts/bootstrapDaterangerpickerPublic.phtml');
?>
<script type="text/javascript" src="/js/echartsCtl.js"></script>
<script src="/js/linechart/js/ajax.js"></script>
<!--    初始化echarts对比字段控制器-->
<script type="text/javascript">
    //折线图输入数据配置
    var lineConfig = {
        myLegend: ['收入(元)', '曝光量', '点击量', '点击率', 'eCPM(元)', 'eCPC(元)'],
        myLegendId: ['income', 'imp', 'clk', 'ctr', 'ecpm', 'ecpc']
    };
    //初始化广告位类型
    currentroleslotclassAPI(currentroleslotclassAPIonSuccess);
    function currentroleslotclassAPIonSuccess(result) {
        var req = JSON.parse(result);
        if (req.status == 1) {
            var data = req.data;
            var option = '';
            for (var key in data) {
                option += '<option value="' + key + '">' + data[key] + '</option>';
            }
            $('#slot_class').html(option);
        } else {
            layer.msg(req.msg);
        }
    }
    //初始化广告位
    fetchmediaslotstructAPI(fetchmediaslotstructAPIonSuccess);
    function fetchmediaslotstructAPIonSuccess(result) {
        var req = JSON.parse(result);
        console.log(req);
        if (req.status == 1) {
            var data = req.data;
            var option = '';
            for (var i = 0; i < data.length; i++) {
                option += '<optgroup label="' + data[i].name + '">';
                var slotArry = data[i].child;
                for (var j = 0; j < slotArry.length; j++) {
                    option += '<option value="' + slotArry[j].id + '">' + slotArry[j].name + '</option>';
                }
                option += '</optgroup>';
            }
            $('#slot').html(option);
        } else {
            layer.msg(req.msg);
        }
    }
    var nowTime = {
        start:moment().subtract('days', 1),
        end:moment().subtract('days', 1)
    }

    var mediasessiontimeStart = window.sessionStorage.getItem('mediasessiontimeStart');
    var mediasessiontimeEnd = window.sessionStorage.getItem('mediasessiontimeEnd');

    if(mediasessiontimeStart != null){
        nowTime.start = mediasessiontimeStart;
    }
    if(mediasessiontimeEnd != null){
        nowTime.end = mediasessiontimeEnd;
    }
    searchDate_daterangepicker(nowTime.start, nowTime.end, nowTime.end);
//    searchDate_daterangepicker(moment().subtract('days', 1), moment().subtract('days', 1), moment().subtract('days', 1));
//    searchDate_daterangepicker(moment(), moment(), moment());
    function searchDate_daterangepicker(startDate, endDate, maxDate) {
        $('#searchDate').daterangepicker({
            startDate: startDate,
            endDate: endDate,
            maxDate: maxDate, //最大时间
            minDate: moment('1970-01-01'), //最小时间
            dateLimit: {
                days: 365
            }, //起止时间的最大间隔
            showDropdowns: true,
            showWeekNumbers: false, //是否显示第几周
            timePicker: false, //是否显示小时和分钟
            timePickerIncrement: 60, //时间的增量，单位为分钟
            timePicker12Hour: false, //是否使用12小时制来显示时间
            ranges: {
//                '今日': [moment().startOf('day'), moment()],
                '昨天': [moment().subtract('days', 1).startOf('day'), moment().subtract('days', 1).endOf('day')],
                '过去7天': [moment().subtract('days', 7), moment().subtract('days', 1)],
                '过去14天': [moment().subtract('days', 14), moment().subtract('days', 1)],
                '过去21天': [moment().subtract('days', 21), moment().subtract('days', 1)],
                '过去30天': [moment().subtract('days', 30), moment().subtract('days', 1)],
                '上个月': [new Date()
                    .setFullYear(new Date().getMonth() == 0 ? new Date().getFullYear() - 1 : new Date().getFullYear(), new Date().getMonth() == 0 ? 11 : new Date().getMonth() - 1, 1),
                    moment().subtract('days', new Date().getDate())]
            },
            showCustomRangeLabel: false,
            alwaysShowCalendars: true,
            linkedCalendars: false,

            opens: 'top', //日期选择框的弹出位置
            buttonClasses: ['btn btn-default'],
            applyClass: 'btn-small btn-primary blue',
            cancelClass: 'btn-small',

            separator: ' to ',
            locale: {
                applyLabel: '确定',
                cancelLabel: '取消',
                fromLabel: '起始时间',
                toLabel: '结束时间',
                customRangeLabel: '自定义',
                daysOfWeek: ['日', '一', '二', '三', '四', '五', '六'],
                monthNames: ['一月', '二月', '三月', '四月', '五月', '六月',
                    '七月', '八月', '九月', '十月', '十一月', '十二月'],
                firstDay: 1,
                format: 'YYYY/MM/DD' //控件中from和to 显示的日期格式
            }
        }, function (start, end, label) {
            window.sessionStorage.setItem('mediasessiontimeStart', start.format('YYYY/MM/DD'));
            window.sessionStorage.setItem('mediasessiontimeEnd', end.format('YYYY/MM/DD'));
            $('#searchDate').val(start.format('YYYY/MM/DD') + ',' + end.format('YYYY/MM/DD'));
        });
    }

    var ListPageConfig = {
        tableId: '#table',   // 表格id
        tableIndexCol: 'uid', //数据索引字段 一般为 uid 或者 id
        func: function (result) {
            //折线图处理代码
            {
                var searchDate = $('#searchDate').val().replace(' - ', ',').split(',');//查询日期
                var slot_class = '';//广告位类型筛选
                var slot_class_val = $("#slot_class").val();
                if (slot_class_val !== null) {
                    slot_class = slot_class_val.join(',');
                }
                var slot = '';//广告位筛选
                var slot_val = $("#slot").val();
                if (slot_val !== null) {
                    slot = slot_val.join(',');
                }
                var dimension = 'date';//维度拆分
                if ($('#dimensionSplit').val() == '2') {
                    dimension = 'slot';
                }
                var begin = searchDate[0].replace(/\//g, '');
                var end = searchDate[1].replace(/\//g, '');
                var url = '/alliancereport/allianceslot?action_name=allianceslotAction&offset=0&limit=1000000&begin=' + begin + '&end=' + end + '&slot=' + slot + '&slot_class=' + slot_class + '&dimension=' + dimension;
                myAjax("GET", url, true, function (result) {
                    var params = {};
                    var searchDate = $('#searchDate').val().replace(' - ', ',').split(',');//查询日期
                    params['begin'] = searchDate[0].replace(/\//g, '');
                    params['end'] = searchDate[1].replace(/\//g, '');
                    var data = JSON.parse(result);
                    var temp = data["data"]["chart"];
                    temp = {
                        status: data.status,
                        msg: data.msg,
                        data: temp
                    };
                    temp = JSON.stringify(temp);
                    renderCurrentLineDaily(temp);
                    if (params["begin"] === params["end"]) {
                        dataCache.date[0] = searchDate[0].replace(/\//g, '.');
                        $("#timeControl0").html(searchDate[0].replace(/\//g, '.'));
                    } else {
                        var str = searchDate[0].replace(/\//g, '.') + " - " + searchDate[1].replace(/\//g, '.');
                        dataCache.date[0] = str;
                        $("#timeControl0").html(str);
                    }

                    var obj1 = document.getElementById("timeIcon1");
                    var obj2 = document.getElementById("timeControl1");
                    obj1.style.opacity = 0;
                    obj2.style.opacity = 0;

                    var timeshow = document.getElementById("myTimeControl");
                    timeshow.style.left = 54 + "%";
                })
            }
        },
        url: {},
        reRequest: function () {//改变筛选项并重新发送请求
            //筛选清除页码cookie
            List.$table.bootstrapTable('deleteCookie', ['pageNumber']);
            List.$table.bootstrapTable('refresh', {
                query: {offset: 0}
            });
        },
        showDetail: false,         //是否显示详细信息按钮
        action: {},
        updateShowColumns: function () {//更新列表中列的显示/隐藏状态
            var dimensionSplit = $('#dimensionSplit').val();
            var columns = [
                {
                    field: '',
                    title: '',
                    formatter: function (value, row, index) {
                        if (index === 0) {
                            return '合计'
                        }
                        return '';
                    },
                    width: '35px',
                    cellStyle: function (value, row, index, field) {
                        if (index === 0) {
                            return {
                                classes: 'totleCell'
                            }
                        }
                        return {}
                    }
                },
                {
                    field: 'period_date',
                    title: '日期',
                    sortable: true,
                    visible: dimensionSplit == '1',
                    formatter: function (value, row, index) {
                        if (typeof value === 'string') {//数据维度：查询日期或对比日期
                            return value;
                        }
                        else if (typeof value === 'object' && value instanceof Array) {//数据维度：不限
                            value.forEach(function (dataValue, item, data) {
                                if (typeof dataValue === 'string') {
                                    if (dataValue == null && dataValue == '') {
                                        value[item] = '-';
                                    }
                                } else if (typeof dataValue === 'object' && dataValue instanceof Array) {
                                    dataValue.forEach(function (childValue, childItem, childData) {
                                        if (childValue == null && childValue == '') {
                                            dataValue[childItem] = '-';
                                        }
                                    });
                                    value[item] = dataValue.join('至');
                                }
                            });
                            return value.join('<br/><p class="compareLineInterval"></p>');
                        }
                        return value;
                    }
                },
                {
                    field: 'slot_name',
                    title: '广告位',
//                    width:'100px',
                    visible: dimensionSplit == '2'
                }, {
                    field: 'slot_class_name',
                    title: '广告位类型',
                    visible: dimensionSplit == '2'
                }, {
                    field: 'media_name',
                    title: '所属媒体',
                    visible: dimensionSplit == '2'
                }, {
                    field: 'imp',
                    title: '曝光量',
                    sortable: true,
                    formatter: function (value, row, index) {
                        if (typeof value === 'string') {//数据维度：查询日期或对比日期
                            return splitK(value);
                        }
                        else if (typeof value === 'object' && value instanceof Array) {//数据维度：不限
                            value.forEach(function (dataValue, item, data) {
                                if (dataValue == null || dataValue == '') {
                                    value[item] = '-';
                                } else {
                                    value[item] = splitK(dataValue);
                                }
                            });
                            return value.join('<br/><p class="compareLineInterval"></p>');
                        }
                        return value;
                    }
                }, {
                    field: 'clk',
                    title: '点击量',
                    sortable: true,
                    formatter: function (value, row, index) {
                        if (typeof value === 'string') {//数据维度：查询日期或对比日期
                            return splitK(value);
                        }
                        else if (typeof value === 'object' && value instanceof Array) {//数据维度：不限
                            value.forEach(function (dataValue, item, data) {
                                if (dataValue == null || dataValue == '') {
                                    value[item] = '-';
                                } else {
                                    value[item] = splitK(dataValue);
                                }
                            });
                            return value.join('<br/><p class="compareLineInterval"></p>');
                        }
                        return value;
                    }
                }, {
                    field: 'ctr',
                    title: '点击率',
                    sortable: true,
                    formatter: function (value, row, index) {
                        return value == null ? null : strToPercent(value);
                    }
                }, {
                    field: 'income',
                    title: '收入(元)',
                    sortable: true,
                    formatter: function (value, row, index) {
                        if (typeof value === 'string') {//数据维度：查询日期或对比日期
                            return splitK(value);
                        }
                        else if (typeof value === 'object' && value instanceof Array) {//数据维度：不限
                            value.forEach(function (dataValue, item, data) {
                                if (dataValue == null || dataValue == '') {
                                    value[item] = '-';
                                } else {
                                    value[item] = splitK(dataValue);
                                }
                            });
                            return value.join('<br/><p class="compareLineInterval"></p>');
                        }
                        return value;
                    }
                }, {
                    field: 'ecpm',
                    title: 'eCPM(元)',
                    sortable: true,
                    formatter: function (value, row, index) {
                        if (typeof value === 'string') {//数据维度：查询日期或对比日期
                            return splitK(value);
                        }
                        else if (typeof value === 'object' && value instanceof Array) {//数据维度：不限
                            value.forEach(function (dataValue, item, data) {
                                if (dataValue == null || dataValue == '') {
                                    value[item] = '-';
                                } else {
                                    value[item] = splitK(dataValue);
                                }
                            });
                            return value.join('<br/><p class="compareLineInterval"></p>');
                        }
                        return value;
                    }
                }, {
                    field: 'ecpc',
                    title: 'eCPC(元)',
                    sortable: true,
                    formatter: function (value, row, index) {
                        if (typeof value === 'string') {//数据维度：查询日期或对比日期
                            return splitK(value);
                        }
                        else if (typeof value === 'object' && value instanceof Array) {//数据维度：不限
                            value.forEach(function (dataValue, item, data) {
                                if (dataValue == null || dataValue == '') {
                                    value[item] = '-';
                                } else {
                                    value[item] = splitK(dataValue);
                                }
                            });
                            return value.join('<br/><p class="compareLineInterval"></p>');
                        }
                        return value;
                    }
                }];
//                    根据维度拆分的值，显示不同的列
            List.$table.bootstrapTable('refreshOptions', {columns: columns});
        },
        toolbar: function () {
            $("input[type='checkbox'][name='echartsCtl']").bind('change', function () {
                ListPageConfig.reRequest();
                ListPageConfig.func();//重新渲染echarts图
            });

            $("#searchDate").bind('change', function () {
                ListPageConfig.reRequest();
                ListPageConfig.func();//重新渲染echarts图
            });

            $("#slot_class").bind('change', function () {
                ListPageConfig.reRequest();
                ListPageConfig.func();//重新渲染echarts图
            });

            $("#slot").bind('change', function () {
                ListPageConfig.reRequest();
                ListPageConfig.func();//重新渲染echarts图
            });

            $("#dimensionSplit").bind('change', function () {//媒体筛选
                ListPageConfig.updateShowColumns();
                ListPageConfig.reRequest();
            });
        },
        table: {//表格参数
            height: undefined,//定义表格的高度
            undefinedText: '-',//当数据为undefined时显示的字符
            striped: true,//设置为 true 会有隔行变色效果
            sortName: undefined,//定义排序列,通过url方式获取数据填写字段名，否则填写下标
            sortOrder: 'desc',//定义排序方式 'asc' 或者 'desc'
            sortStable: true,//设置为 true 将获得稳定的排序，我们会添加_position属性到 row 数据中。
            url: '/alliancereport/allianceslot',//服务器数据的加载地址
            queryParams: function queryParams(params) {//请求服务器数据时，你可以通过重写参数的方式添加一些额外的参数
                var searchDate = $('#searchDate').val().replace(' - ', ',').split(',');//查询日期
                var slot_class = '';//广告位类型筛选
                var slot_class_val = $("#slot_class").val();
                if (slot_class_val !== null) {
                    slot_class = slot_class_val.join(',');
                }
                var slot = '';//广告位筛选
                var slot_val = $("#slot").val();
                if (slot_val !== null) {
                    slot = slot_val.join(',');
                }
                var dimension = 'date';//维度拆分
                if ($('#dimensionSplit').val() == '2') {
                    dimension = 'slot';
                }
                params['begin'] = searchDate[0].replace(/\//g, '');
                params['end'] = searchDate[1].replace(/\//g, '');
                params['slot_class'] = slot_class;
                params['slot'] = slot;
                params['dimension'] = dimension;
                if ($('#dimensionSplit').val() == '2' && params['sort'] == 'date') {
                    params['sort'] = undefined;
                }
                return params;
            },
            responseHandler: function (res) {//加载服务器数据之前的处理程序，可以用来格式化数据。
                if (res.status == 1) {
                    return {
                        rows: res.data.report.rows,
                        total: parseInt(res.data.report.total)
                    }
                } else {
                    layer.msg(res.msg);
                    return {rows: [], total: 0};
                }
            },
            toolbar: '#toolbar',//一个jQuery 选择器，指明自定义的toolbar 例如:#toolbar, .toolbar.
            searchAlign: 'left',
            pagination: true,//	设置为 true 会在表格底部显示分页条
            paginationLoop: true,//	设置为 true 启用分页条无限循环的功能。
            onlyInfoPagination: false,//设置为 true 只显示总数据数，而不显示分页按钮。需要 pagination='True'
            sidePagination: 'server',//设置在哪里进行分页，可选值为 'client' 或者 'server'。设置 'server'时，必须设置 服务器数据地址（url）或者重写ajax方法
            pageNumber: 1,//如果设置了分页，首页页码
            pageSize: 50,  //如果设置了分页，页面数据条数
            pageList: [30, 50, 100],//如果设置了分页，设置可供选择的页面数据条数。设置为All 则显示所有记录。
            search: false,//是否启用搜索框
            showFooter: false,//是否显示列脚
            showColumns: true,//是否显示 内容列下拉框
            showRefresh: true,//是否显示 刷新按钮
            showToggle: false,//是否显示 切换试图（table/card）按钮
            showPaginationSwitch: false,//是否显示 数据条数选择框
            paginationVAlign: 'bottom',//指定 分页条 在垂直方向的位置。'top' or 'bottom' or 'bonth'
            paginationPreText: '上一页',//指定分页条中上一页按钮的图标或文字
            paginationNextText: '下一页',//指定分页条中下一页按钮的图标或文字
            clickToSelect: false,//设置true 将在点击行时，自动选择rediobox 和 checkbox
            singleSelect: false,//设置True 将禁止多选
            checkboxHeader: false,//设置false 将在列头隐藏check-all checkbox
            maintainSelected: false,//设置为 true 在点击分页按钮或搜索按钮时，将记住checkbox的选择项
            sortable: true,//设置为false 将禁止所有列的排序
            silentSort: true,//设置为 false 将在点击分页按钮时，自动记住排序项。仅在 sidePagination设置为 server时生效.
            cookie: true,
            cookieIdTable: 'replacebyListJS',
            cookiesEnabled: ['bs.table.pageNumber'],
            cookiePath: '/',
            rowStyle: function (row, index) {//自定义行样式 参数为：row: 行数据 index: 行下标 返回值可以为class或者css
                return {};
//                if ((index % 2) !== 0) {//demo
//                    return {
//                        css: {'color': 'red'}
//                    }
//                }else{
//                    return{}
//                }
            },
            rowAttributes: function rowAttributes(row, index) {//自定义行属性 参数为：row: 行数据 index: 行下标 返回值可以为class或者css 支持所有自定义属性
                return {
//                    'data-id': row.guid,
//                    'data-htmlpath': row.htmlPath,
//                    'data-xmlpath': row.xmlPath
                }
            },
            columns: [
                {
                    field: '',
                    title: '',
                    formatter: function (value, row, index) {
                        if (index === 0) {
                            return '合计'
                        }
                        return '';
                    },
                    width: '35px',
                    cellStyle: function (value, row, index, field) {
                        if (index === 0) {
                            return {
                                classes: 'totleCell'
                            }
                        }
                        return {}
                    }
                }, {
                    field: 'slot_name',
                    title: '广告位',
//                    width: '100px'
                }, {
                    field: 'slot_class_name',
                    title: '广告位类型'
                }, {
                    field: 'media_name',
                    title: '所属媒体'
                }, {
                    field: 'imp',
                    title: '曝光量',
                    sortable: true,
                    formatter: function (value, row, index) {
                        if (typeof value === 'string') {//数据维度：查询日期或对比日期
                            return splitK(value);
                        }
                        else if (typeof value === 'object' && value instanceof Array) {//数据维度：不限
                            value.forEach(function (dataValue, item, data) {
                                if (dataValue == null || dataValue == '') {
                                    value[item] = '-';
                                } else {
                                    value[item] = splitK(dataValue);
                                }
                            });
                            return value.join('<br/><p class="compareLineInterval"></p>');
                        }
                        return value;
                    }
                }, {
                    field: 'clk',
                    title: '点击量',
                    sortable: true,
                    formatter: function (value, row, index) {
                        if (typeof value === 'string') {//数据维度：查询日期或对比日期
                            return splitK(value);
                        }
                        else if (typeof value === 'object' && value instanceof Array) {//数据维度：不限
                            value.forEach(function (dataValue, item, data) {
                                if (dataValue == null || dataValue == '') {
                                    value[item] = '-';
                                } else {
                                    value[item] = splitK(dataValue);
                                }
                            });
                            return value.join('<br/><p class="compareLineInterval"></p>');
                        }
                        return value;
                    }
                }, {
                    field: 'ctr',
                    title: '点击率',
                    sortable: true,
                    formatter: function (value, row, index) {
                        return value == null ? null : strToPercent(value);
                    }
                }, {
                    field: 'income',
                    title: '收入(元)',
                    sortable: true,
                    formatter: function (value, row, index) {
                        if (typeof value === 'string') {//数据维度：查询日期或对比日期
                            return splitK(value);
                        }
                        else if (typeof value === 'object' && value instanceof Array) {//数据维度：不限
                            value.forEach(function (dataValue, item, data) {
                                if (dataValue == null || dataValue == '') {
                                    value[item] = '-';
                                } else {
                                    value[item] = splitK(dataValue);
                                }
                            });
                            return value.join('<br/><p class="compareLineInterval"></p>');
                        }
                        return value;
                    }
                }, {
                    field: 'ecpm',
                    title: 'eCPM(元)',
                    sortable: true,
                    formatter: function (value, row, index) {
                        if (typeof value === 'string') {//数据维度：查询日期或对比日期
                            return splitK(value);
                        }
                        else if (typeof value === 'object' && value instanceof Array) {//数据维度：不限
                            value.forEach(function (dataValue, item, data) {
                                if (dataValue == null || dataValue == '') {
                                    value[item] = '-';
                                } else {
                                    value[item] = splitK(dataValue);
                                }
                            });
                            return value.join('<br/><p class="compareLineInterval"></p>');
                        }
                        return value;
                    }
                }, {
                    field: 'ecpc',
                    title: 'eCPC(元)',
                    sortable: true,
                    formatter: function (value, row, index) {
                        if (typeof value === 'string') {//数据维度：查询日期或对比日期
                            return splitK(value);
                        }
                        else if (typeof value === 'object' && value instanceof Array) {//数据维度：不限
                            value.forEach(function (dataValue, item, data) {
                                if (dataValue == null || dataValue == '') {
                                    value[item] = '-';
                                } else {
                                    value[item] = splitK(dataValue);
                                }
                            });
                            return value.join('<br/><p class="compareLineInterval"></p>');
                        }
                        return value;
                    }
                }]
        }
    };
    //下载报表
    $("#downloadTable").on('click', function () {
        var searchDate = $('#searchDate').val().replace(' - ', ',').split(',');//查询日期
        var slot_class = '';//广告位类型筛选
        var slot_class_val = $("#slot_class").val();
        if (slot_class_val !== null) {
            slot_class = slot_class_val.join(',');
        }
        var slot = '';//广告位筛选
        var slot_val = $("#slot").val();
        if (slot_val !== null) {
            slot = slot_val.join(',');
        }
        var dimension = 'date';//维度拆分
        if ($('#dimensionSplit').val() == '2') {
            dimension = 'slot';
        }
        var begin = searchDate[0].replace(/\//g, '');
        var end = searchDate[1].replace(/\//g, '');
        var url = '/alliancereport/exportcsv?action_name=allianceslotAction&offset=0&limit=1000000&begin=' + begin + '&end=' + end + '&slot=' + slot + '&slot_class=' + slot_class + '&dimension=' + dimension;
        window.open(encodeURI(url));
    });
    var auth = getAuthorityByUrl('/alliancereport/allianceslotview');
    function checkAuthority() {
        if (auth == 0) {
            toFirstLegalPage();
        }
    }
    checkAuthority();
</script>

<!--折线图组件js start-->
<!--折线图必须在lingConfig后面引入，因为没有写成闭包-->
<!--<script src="/js/linechart/js/ajax.js"></script>-->
<script src="/js/linechart/js/domReady.js"></script>
<script src="/js/linechart/js/macarons.js"></script>
<script src="/js/linechart/js/lineChart.js"></script>
<!--折线图组件js end-->
<table id="table" class="list-table"></table>

<?php
echo $this->renderFile('@app/views/layouts/listAd.phtml');
?>