<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta charset="utf-8"/>
    <title>DL广告投放系统</title>
    <meta name="description" content="overview &amp; stats"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
    <link rel="stylesheet" href="/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/css/index.css?v=11"/>
</head>
<body style="min-width: 1024px">
<div style="background: #04d6ac;position: fixed;top: 0;right: 0;left: 0;z-index: 100;height: 60px;">
    <div class="container-fluid" style="padding: 13px 30px 0;">
        <div class="row head">
            <div class="col-xs-12 col-md-12 headimg">
                <img src="../img/images/head.png">
                <div class="login_nav_box" style="line-height: 37px;">
                    <a href="http://www.deepleaper.com/">首页</a>
                    <a href="http://www.deepleaper.com/newmedia.html">媒体</a>
                    <a href="http://www.deepleaper.com/newad.html">广告主</a>
                    <a href="http://www.deepleaper.com/aboutUs.html">关于我们</a>
                    <a href="https://www.lagou.com/gongsi/139866.html">加入我们</a>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="login-big"
     style="display:none;position: absolute;top: 50%;left: 50%;-webkit-transform: translate(-50%,-50%);-moz-transform: translate(-50%,-50%);-ms-transform: translate(-50%,-50%);-o-transform: translate(-50%,-50%);transform: translate(-50%,-50%);">
    <div class="login-div">
        <form id="formLogin" action="/index/login" method="post">
            <input type="hidden" name="ajax" value="1">
            <h2>用&nbsp;&nbsp;户&nbsp;&nbsp;登&nbsp;&nbsp;录</h2>
            <div class="login-input">
                <img src="/images/e-icon.png">
                <input type='text' placeholder="E-mail" name="username"
                       style="width: 200px; box-shadow: 0 0 0 1000px #ededed inset;">
            </div>
            <div class="login-input">
                <img src="/images/p-icon.png">
                <input type='password' placeholder="Password" name="passwd"
                       style="width: 200px;  box-shadow: 0 0 0 1000px #ededed inset;">
            </div>

            <div class="login-tip" style="display:none;">
                <span class="triangle"></span>
                <span class="tip">ID 或密码不正确</span>
            </div>

            <p class="forget" style="visibility: hidden">忘记密码</p>
            <a id="signbtn" class="sign-in" href="javascript:void(0)" onclick="subgo()">登&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;录</a>
        </form>
    </div>
</div>

<div class="login_wrapper" style="display: block">
    <div class="login_sys">
        <div class="media_sys active" id="media_sys">媒体主</div>
        <div class="ad_sys" id="ad_sys">广告主</div>
    </div>
    <div class="login_content" id="media_content">
        <p class="login_logo">LOGIN</p>
        <div class="media_choose">
            <input type="radio" name="media_type" value="selfsupport" id="self" checked><label for="self"
                                                                                               class="self_label checked">自营</label>
            <input type="radio" name="media_type" value="alliance" id="union"><label for="union"
                                                                                     class="union_label ">联盟</label>
        </div>
        <div class="login_user_wrapper">
            <label>EMAIL ADDRESS</label>
            <input type="text" name="username" class="username" spellcheck="false">
        </div>
        <div class="login_password_wrapper">
            <label>PASSWORD</label>
            <input type="password" name="password" class="password">
        </div>
        <div class="login_submit_wrapper">
            <div class="login_submit_btn" id="media_login">
                login&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;>>
            </div>
            <div class="forget">
                FORGET PASSWORD
            </div>
        </div>
    </div>
    <div class="login_content" id="ad_content" style="display: none">
        <p class="login_logo">LOGIN</p>
        <div class="media_choose" style="visibility: hidden">
            <input type="radio"><label>1</label>
            <input type="radio"><label>2</label>
        </div>
        <div class="login_user_wrapper">
            <label>EMAIL ADDRESS</label>
            <input type="text" name="username" class="username" spellcheck="false">
        </div>
        <div class="login_password_wrapper">
            <label>PASSWORD</label>
            <input type="password" name="password" class="password">
        </div>
        <div class="login_submit_wrapper">
            <div class="login_submit_btn" id="ad_login">
                login&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;>>
            </div>
            <div class="forget">
                FORGET PASSWORD
            </div>
        </div>
    </div>
</div>

</body>
</html>
<script src="/js/jquery-1.11.3.min.js" type="text/javascript"></script>
<script src="/js/layer/layer.js" type="text/javascript"></script>
<script src="/js/DeepLeaperAPI.js" type="text/javascript"></script>
<script>
    $("#media_content .password").keydown(function (event) {
        if (event.keyCode == 13) {
            $("#media_login").click();
        }
    });
    $("#ad_content .password").keydown(function (event) {
        if (event.keyCode == 13) {
            $("#ad_login").click();
        }
    });
    //    媒体主／广告主UI切换
    $("#media_sys").bind('click', function () {
        $(this).addClass('active');
        $("#ad_sys").removeClass('active');
        $("#ad_content").fadeOut(100);
        setTimeout(function () {
            $("#media_content").fadeIn();
        }, 100)
    });
    $("#ad_sys").bind('click', function () {
        $(this).addClass('active');
        $("#media_sys").removeClass('active');
        $("#media_content").fadeOut(100);
        setTimeout(function () {
            $("#ad_content").fadeIn();
        }, 100)
    });
    //    自营／联盟UI切换
    $("input[name=media_type]").change(changeMediaStatus);
    function changeMediaStatus() {
        $("input[name=media_type]").each(function () {
            if ($(this).prop('checked')) {
                $("label[for=" + $(this).attr('id') + "]").addClass('checked');
            } else {
                $("label[for=" + $(this).attr('id') + "]").removeClass('checked');
            }
        })
    }
    //    媒体主登录
    $("#media_login").bind('click', function () {
        var username = $("#media_content .username");
        var password = $("#media_content .password");
        if (username.val() == "") {
            layer.msg('用户名不能为空');
            username.focus();
            return false;
        } else if (password.val() == "") {
            layer.msg('密码不能为空');
            password.focus();
            return false;
        }
        var media_type = $("input[name=media_type]:checked").val();//平台角色
        loginAPI('media', media_type, username.val(), password.val(), loginOnsuccessFun)
    });
    //    广告主登录
    $("#ad_login").bind('click', function () {
        var username = $("#ad_content .username");
        var password = $("#ad_content .password");
        if (username.val() == "") {
            layer.msg('用户名不能为空');
            username.focus();
            return false;
        } else if (password.val() == "") {
            layer.msg('密码不能为空');
            password.focus();
            return false;
        }
        loginAPI('client', 'alliance', username.val(), password.val(), loginOnsuccessFun)
    });
    function loginOnsuccessFun(result) {
        var req = JSON.parse(result);
        console.log(req);
        if (req.status == 1) {
            window.location = req.data;
        } else {
            layer.msg(req.msg);
        }
    }
</script>
