export const USERINFO_INIT = "USERINFO_INIT";
export const TIME_SET  = "TIME_SET ";
// 数据概览
export const COVERVIEW_SET_CURRENT = "COVERVIEW_SET_CURRENT";
export const COVERVIEW_SET_COMPARE = "COVERVIEW_SET_COMPARE";
// 折线图
export const LINECHART_CURRENT_SET = "LINECHART_CURRENT_SET";
export const LINECHART_COMPARE_SET = "LINECHART_COMPARE_SET";
//关键词
export const KEYWORD_CURRENT_SET = "KEYWORD_CURRENT_SET";
export const KEYWORD_COMPARE_SET = "KEYWORD_COMPARE_SET";
//广告组
export const AD_GROUP_TOP = "AD_GROUP_TOP";
//广告计划
export const AD_PLAN_TOP = "AD_PLAN_TOP";
