<?php
    echo $this->partial('layout/listPublicHeader.phtml');
?>
<div id = "toolbar">
		<?php if ($this->userPower['power'] == 'admin') { ?>
		<div class = "btn-group pull-left">
			
			<a class = "btn btn-warning plus"><i class = "glyphicon glyphicon-plus"></i> 添加</a>
			
			<button id = "dropdown" class = "btn btn-warning dropdown-toggle" data-toggle = "dropdown" disabled><span
					class = "caret"></span></button>
			<ul class = "dropdown-menu">
				<li><a href = "#" class = "allremove"><i class = "glyphicon glyphicon-remove"></i> 删除</a></li>

			</ul>
		</div>
		<?php }?>
		<div class = "input-group pull-left paddingleft10" style = 'width:300px;'>
			<input type = "text" id = "searchKeyword" class = "form-control" placeholder = "搜索" value = "" name = "search">
		
	   
		
		
			<span class = "input-group-btn">
				<a id = "ok" class = "btn btn-default dropdown-toggle deepleaper-search-btn" type = "button" data-toggle = "dropdown"><span
						class = "glyphicon glyphicon-search"></span></a>
			</span>
		</div>
	</div>
<table id = "table" class="list-table"></table>

<script>

    var ListPageConfig = {
        tableId:'#table',   // 表格id
        tableIndexCol :'uid', //数据索引字段 一般为 uid 或者 id
        table : {           //表格配置
            url: '/client/category',
            queryParams: 'queryParams',
            toolbar: '#toolbar',
            showColumns: true,
            searchAlign:'left',
            pagination: true,
            pageSize: 25,  //获取所有数据,建立二级结构
            sortOrder: 'desc',
            detailView:true,
            sidePagination: 'server',
            cookie: true,
            cookieIdTable: 'saveId',
            onExpandRow:function(index,row,$detail){
                 $detail.html('<table></table>').find('table').bootstrapTable({
                    columns: ListPageConfig.table.columns,
                    data: row.rows
                });
            },
            columns: [{
                field: 'name',
                title: '行业名称'
            },{
                field: 'info',
                title: '备注'
            }, {
            
                field: 'create_time',
                title: '创建时间',
                sortable:true,
            }, {
                field: 'createUserName',
                title: '创建/修改人'
            }, {
                field: 'do',
                title: '操作',
                align: 'center',
                formatter: 'List.operateFormatter',
                events: 'List.operateEvents',
            }]
        },
        url:{
            add         : '/client/categoryadd',         //添加 数据 html 地址
            edit        : '/client/categoryedit',         //编辑数据 html 地址
            del         : '/client/categorydel' ,         //删除数据地址
            detail      : false                      //详细内容地址,为空则取编辑的地址
        },
        title:{
            addTitle:'添加广告主分类',
            editTitle:'编辑广告主分类',
        },
        showDetail:false         //是否显示详细信息按钮
    }

</script>


<?php
    echo $this->partial('layout/listPublicFooter.phtml');
?>