<?php
echo $this->partial('layout/listPublicHeader.phtml');
?>
    <script>

        var ListPageConfig = {
            tableId:'#table',   // 表格id
            tableIndexCol :'uid', //数据索引字段 一般为 uid 或者 id
            table : {           //表格配置
                url: '/user/agency',
                queryParams: 'queryParams',
                toolbar: '#toolbar',
                showColumns: true,
                searchAlign:'left',
                pagination: true,
                pageSize: 50,  //获取所有数据,建立二级结构
                sortOrder: 'desc',
                sidePagination: 'server',
                cookie: true,
                cookieIdTable: 'saveId',
                columns: [{
                    checkbox: true
                }, {
                    field: 'mail',
                    title: '账号'
                },{
                    field: 'name',
                    title: '姓名'
                },  {
                    field: 'belong',
                    title: '所属代理商'
                },  {
                    field: 'login_count',
                    title: '登录次数'
                }, {
                    field: 'is_deleted',
                    title: '启用状态',
                    formatter:function(value, row, index){
                        if(0 == parseInt(value)){
                            return '可用';
                        }else{
                            return '<span style="color:red">已禁用</span>';
                        }
                    }
                }, {
                    field: 'finance',
                    title: '财务状态',
                    formatter:function(value, row, index){
                        if(0 == parseInt(value)){
                            return '开通';
                        }else{
                            return '关闭';
                        }
                    }
                },    {
                    field: 'create_time',
                    title: '创建时间',
                    sortable:true,
                }, {
                    field: 'do',
                    title: '操作',
                    align: 'center',
                    formatter: 'List.operateFormatter',
                    events: 'List.operateEvents',
                }]
            },
            url:{
                add         : '/user/agencyedit',         //添加 数据 html 地址
                edit        : '/user/agencyedit',         //编辑数据 html 地址
                del         : '/user/agencydel' ,         //删除数据地址
                detail      : false                      //详细内容地址,为空则取编辑的地址
            },
            title:{
                addTitle:'添加代理商用户',
                editTitle:'编辑代理商用户',
            },
            showDetail:false         //是否显示详细信息按钮
        }

    </script>


<?php
echo $this->partial('layout/listPublicFooter.phtml');
?>