<form id="add" method="post" action="/user/clientsave" class="form-horizontal list-form" novalidate="novalidate">

    <div class="form-group ">

        <label class="col-sm-3 control-label">邮箱</label>
        <div class="col-sm-6 ">
            <input id="mail" type="text" name="mail" class="form-control" check-type="required" required-message="不能为空。">
        </div>
    </div>

    <div class="form-group ">
        <label class="col-sm-3 control-label">姓名</label>
        <div class="col-sm-6 ">
            <input id="name" type="text" name="name" class="form-control" check-type="required" required-message="不能为空。">
        </div>
    </div>

    <div class="form-group ">
        <label class="col-sm-3 control-label">密码</label>
        <div class="col-sm-6 ">
            <input id="password" type="password" name="password" class="form-control" check-type="required" required-message="不能为空。">
        </div>
    </div>
    <div class="form-group ">
        <label class="col-sm-3 control-label">重复密码</label>
        <div class="col-sm-6 ">
            <input id="password2" type="password" name="password2" class="form-control" check-type="required" required-message="不能为空。">
        </div>
    </div>
    
    <div class="form-group ">
        <label class="col-sm-3 control-label">资源类型</label>
        <div class="col-sm-6 ">
            
        	
        	<input type="radio" name="power" id="optionsRadios1" value="agency" <?php if ($this->form['power']== 'agency') echo 'checked="true"' ?>> &nbsp;&nbsp;媒介代理商 
			  &nbsp;  &nbsp;  &nbsp;  &nbsp;
			<input type="radio" name="power" id="optionsRadios2" value="client" <?php if ($this->form['power']== 'client') echo  'checked="true"' ?>>&nbsp;&nbsp;广告主
			
        </div>
    </div>

    <div class="form-group ">
        <label class="col-sm-3 control-label">关联资源</label>
        <div id="power_agence" class="col-sm-6  " >
            <select  name="pid_agence" class="form-control selectpicker" data-live-search="true" check-type="required" required-message="不能为空。">
                <option value=""  >请选择代理商</option>
                <?php foreach($this->agenceList as $key => $val):?>
                    <option value="<?php echo $key;?>"  ><?php echo $val;?></option>
                <?php endforeach;?>
            </select>
            
           
        </div>
        
         <div id="power_client" class="col-sm-6  " style="display:none;">
 
            
            <select  name="pid_client" class="form-control selectpicker" data-live-search="true" check-type="required" required-message="不能为空。" >
                <option value=""  >请选择广告主</option>
                <?php foreach($this->clientList as $key => $val):?>
                    <option value="<?php echo $key;?>"  ><?php echo $val;?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>
	
	<!--
    <div class="form-group ">
        <label class="col-sm-3 control-label">权限</label>
        <div class="col-sm-6 ">
            <select id="permission" class="form-control selectpicker" data-live-search="true"  name="permission">
                <option value="readonly">只读权限</option>
                <option value="full">自助权限</option>
            </select>
        </div>
    </div>

    <div class="form-group ">
        <label class="col-sm-3 control-label">财务数据</label>
        <div class="col-sm-6 ">
            <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default active">
                    <input checked type="radio" name="finance" value="1">开启
                </label>
                <label class="btn btn-default ">
                    <input type="radio" name="finance" value="0">关闭
                </label>
            </div>
        </div>
    </div>
	-->

</form>

<script type="text/javascript">
    $(function(){
    	$('#optionsRadios1').attr("checked","checked");
    	$('#optionsRadios1').click(function(){
    		if($('#optionsRadios1').is(':checked')) {
    			
				$('#power_agence').show();
				$('#power_client').hide();
			}
    	});
    	
    	$('#optionsRadios2').click(function(){
    		if($('#optionsRadios2').is(':checked')) {
				$('#power_agence').hide();
				$('#power_client').show();
			}
    	});
    
	

   
    });
</script>
