

<form id="edit" method="post" action="/user/internalsave" class="form-horizontal list-form" novalidate="novalidate">

    <div class="form-group ">
        <?php if($this->item['mail']){
            ?>
            <input id="uid" type="hidden" name="uid" value="<?php   echo $this->item['uid']; ?>"  >
            <?php
        }; ?>
        <label class="col-sm-3 control-label">邮箱</label>
        <div class="col-sm-6 ">
            <input id="mail" type="text" name="mail" value="<?php   echo $this->item['mail']; ?>"  <?php if($this->item['mail'])    echo 'readonly'; ?>  class="form-control" check-type="required" required-message="不能为空。">
        </div>
    </div>

    <div class="form-group ">
        <label class="col-sm-3 control-label">姓名</label>
        <div class="col-sm-6 ">
            <input id="name" type="text" name="name" value="<?php   echo $this->item['name']; ?>" class="form-control" check-type="required" required-message="不能为空。">
        </div>
    </div>

    <div class="form-group ">
        <label class="col-sm-3 control-label">密码</label>
        <div class="col-sm-6 ">
            <input id="password" type="password" name="password" class="form-control"  >
        </div>
    </div>
    <div class="form-group ">
        <label class="col-sm-3 control-label">重复密码</label>
        <div class="col-sm-6 ">
            <input id="password2" type="password" name="password2" class="form-control"  >
        </div>
    </div>
   
    <div class="form-group ">
        <label class="col-sm-3 control-label">用户类型</label>
        <div class="col-sm-6  ">
            <select name="power" class="form-control selectpicker" data-live-search="true" check-type="required" required-message="不能为空。">
                <?php foreach($this->powerList as $key => $val):?>
                    <option value="<?php echo $key;?>"  <?php if($this->item['power'] == $key) echo 'selected="selected"'?> ><?php echo $val;?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>


	<!--
    <div class="form-group ">
        <label class="col-sm-3 control-label">权限</label>
        <div class="col-sm-6 ">
            <select id="permission" class="form-control selectpicker" data-live-search="true"  name="permission">
                <option  <?php   if( $this->item['permission']  == 'readonly' ){echo 'checked';} ?> value="readonly">只读权限</option>
                <option <?php   if( $this->item['permission']  == 'full' ){echo 'checked';} ?>  value="full">自助权限</option>

            </select>
        </div>
    </div>

    <div class="form-group ">
        <label class="col-sm-3 control-label">财务数据</label>
        <div class="col-sm-6 ">
            <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default <?php   if( $this->item['finance']  == 1 ){echo 'active';} ?> ">
                    <input <?php   if( $this->item['finance']  == 1 ){echo 'checked';} ?>  type="radio" name="finance" value="1">开启
                </label>
                <label class="btn btn-default <?php   if( $this->item['finance']  == 0 || !isset($this->item ) ){echo 'active';} ?>  ">
                    <input <?php   if( $this->item['finance']  == 0 || !isset($this->item ) ){echo 'checked';} ?>  type="radio" name="finance" value="0">关闭
                </label>
            </div>
        </div>
    </div>
	-->

</form>