<!--广告位模板价管理界面-->
<?php
echo $this->partial('layout/listPublicHeader2.phtml');
?>
<table id="table" class="list-table"></table>
<script>
    var ListPageConfig = {
        tableId: '#table',   // 表格id
        tableIndexCol: 'uid', //数据索引字段 一般为 uid 或者 id
        showDetail: false,         //是否显示详细信息按钮
        func: function () {
        },
        table: {//表格参数
            height: undefined,//定义表格的高度
            undefinedText: '-',//当数据为undefined时显示的字符
            striped: true,//设置为 true 会有隔行变色效果
            sortName: undefined,//定义排序列,通过url方式获取数据填写字段名，否则填写下标
            sortOrder: 'desc',//定义排序方式 'asc' 或者 'desc'
            sortStable: true,//设置为 true 将获得稳定的排序，我们会添加_position属性到 row 数据中。
            url: '/user/templateprofitrate',//服务器数据的加载地址
            queryParams: 'queryParams',//请求服务器数据时，你可以通过重写参数的方式添加一些额外的参数
            responseHandler: function (res) {//加载服务器数据之前的处理程序，可以用来格式化数据。
                if (res.status == 1) {
                    return res.data;
                } else {
                    console.log("格式化数据失败");
                    return res;
                }
            },
            toolbar: '#toolbar',//一个jQuery 选择器，指明自定义的toolbar 例如:#toolbar, .toolbar.
            searchAlign: 'left',
            pagination: true,//	设置为 true 会在表格底部显示分页条
            paginationLoop: true,//	设置为 true 启用分页条无限循环的功能。
            onlyInfoPagination: false,//设置为 true 只显示总数据数，而不显示分页按钮。需要 pagination='True'
            sidePagination: 'server',//设置在哪里进行分页，可选值为 'client' 或者 'server'。设置 'server'时，必须设置 服务器数据地址（url）或者重写ajax方法
            pageNumber: 1,//如果设置了分页，首页页码
            pageSize: 50,  //如果设置了分页，页面数据条数
            pageList: [30, 50, 100],//如果设置了分页，设置可供选择的页面数据条数。设置为All 则显示所有记录。
            search: true,//是否启用搜索框
            showFooter: false,//是否显示列脚
            showColumns: true,//是否显示 内容列下拉框
            showRefresh: true,//是否显示 刷新按钮
            showToggle: false,//是否显示 切换试图（table/card）按钮
            showPaginationSwitch: false,//是否显示 数据条数选择框
            paginationVAlign: 'bottom',//指定 分页条 在垂直方向的位置。'top' or 'bottom' or 'bonth'
            paginationPreText: '上一页',//指定分页条中上一页按钮的图标或文字
            paginationNextText: '下一页',//指定分页条中下一页按钮的图标或文字
            clickToSelect: false,//设置true 将在点击行时，自动选择rediobox 和 checkbox
            singleSelect: false,//设置True 将禁止多选
            checkboxHeader: false,//设置false 将在列头隐藏check-all checkbox
            maintainSelected: false,//设置为 true 在点击分页按钮或搜索按钮时，将记住checkbox的选择项
            sortable: true,//设置为false 将禁止所有列的排序
            silentSort: true,//设置为 false 将在点击分页按钮时，自动记住排序项。仅在 sidePagination设置为 server时生效.
            rowStyle: function (row, index) {//自定义行样式 参数为：row: 行数据 index: 行下标 返回值可以为class或者css
                return {};
//                if ((index % 2) !== 0) {//demo
//                    return {
//                        css: {'color': 'red'}
//                    }
//                }else{
//                    return{}
//                }
            },
            rowAttributes: function rowAttributes(row, index) {//自定义行属性 参数为：row: 行数据 index: 行下标 返回值可以为class或者css 支持所有自定义属性
                return {
//                    'data-id': row.guid,
//                    'data-htmlpath': row.htmlPath,
//                    'data-xmlpath': row.xmlPath
                }
            },
            columns: [{//列参数
                checkbox: true
            }, {
                field: 'media_name',
                title: '媒体名称'
            }, {
                field: 'slot_name',
                title: '广告位名称'
            }, {
                field: 'template_name',
                title: '模板名称'
            }, {
                field: 'price',
                title: '模板结算价'
            }, {
                field: 'profit_rate',
                title: '模板价上浮比例(%)',
                editable: {
                    type: 'text',
                    title: '模板价上浮比例',
                    validate: function (v) {
                        if (!v) return '模板价上浮比例不能为空';
                        if (isNaN(v)) return '输入格式错误';
                    }
                }
            }, {
                field: 'profit_price',
                title: '模板竞价底价',
                editable: {
                    type: 'text',
                    title: '模板价上浮比例',
                    validate: function (v) {
                        if (!v) return '模板竞价底价不能为空';
                        if (isNaN(v)) return '输入格式错误';
                    }
                }
            }],
            onEditableSave: function (field, row, oldValue, $el) {
                var profit_rate = row.profit_rate;
                var profit_price = row.profit_price;
                if (field == 'profit_rate') {
                    profit_price = row.price * (1 + (row.profit_rate) / 100);
                } else if (field == 'profit_price') {
                    profit_rate = (row.profit_price - row.price) / row.price * 100;
                }
                var data = [];
                data.push({
                    'uid': row.uid,
                    'profit_rate': profit_rate,
                    'profit_price': profit_price
                });
                $.ajax({
                    type: "post",
                    url: "/user/savetemplateprofitrate",
                    data: JSON.stringify(data),
                    dataType: 'JSON',
                    success: function (data, status) {
                        if (status == "success") {
                            if (data.status == 1) {
                                layer.msg('提交数据成功');
                                List.$table.bootstrapTable('refresh');
                            } else {
                                layer.msg(data.msg);
                            }
                        }
                    },
                    error: function () {
                        layer.msg('编辑失败');
                    },
                    complete: function () {

                    }
                });
            }
        }
    };

    var auth = getAuthorityByUrl('/user/userpermissionview');
    hideChangeBtnIfNeed(auth);
</script>

<table id="table" class="list-table"></table>

<?php
echo $this->partial('layout/listAd.phtml');
?>