
<form id="edit" method="post" action="/order/templatesave" class="form-horizontal list-form" novalidate="novalidate">

    <div class="form-group ">
        <label class="col-sm-3 control-label">模板名称</label>
        <div class="col-sm-6 ">
            <?php echo $item['name'];?>
            
        </div>
    </div>
     
    <div class="form-group ">
        <label class="col-sm-3 control-label">类型</label>
        <div class="col-sm-6 ">
          
					
					<?php foreach ($slotclass_menu  as $k => $v) {
						  if($item['scope'] == $v) {
						 	echo $v;
						  } 
						}
					?>
					
        </div>
    </div>
    
    
    
     <div class="form-group ">
        <label class="col-sm-3 control-label">模板使用说明</label>
        <div class="col-sm-6 ">
            <?php echo $item['info'];?>
        </div>
    </div>
    
    <div class="form-group ">
        <label class="col-sm-3 control-label">模板代码</label>
        <div class="col-sm-6 ">
             <textarea id="code"  name="code" rows="3" cols="50" class="form-control"><?php echo $item['code'];?></textarea>
        </div>
    </div>

    
    
</form>

<script type="text/javascript">

    checkActionAuth('/order/template', 1);
</script>